#!/bin/bash
# init script for the openQRM lxc-storage-plugin
#
# This file is part of openQRM.
#
# openQRM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation.
#
# openQRM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openQRM.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2010, Matthias Rechenburg <matt@openqrm.com>
#

OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/lxc-storage/include/openqrm-plugin-lxc-storage-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/lxc-storage/etc/openqrm-plugin-lxc-storage.conf
OPENQRM_VM_DIR="/var/lib/lxc/"
export OPENQRM_VM_DIR
# get the ip config
openqrm_server_get_config
export resource_openqrmserver=$OPENQRM_SERVER_IP_ADDRESS
export LANG=C
# define wget to use with https
if [ "$OPENQRM_WEB_PROTOCOL" == "https" ]; then
    WGET_NO_CERT_CHECK="--no-check-certificate"
fi
LINE_IFS='
'

function openqrm_plugin_lxc_storage_start() {
	openqrm_plugin_lxc_storage_stop 1>/dev/null 2>&1
	echo "Starting the openQRM lxc-storage-plugin"
	touch $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/lxc-storage/.running
    # start the vm status autostart
    if [ -d "$OPENQRM_VM_DIR" ]; then
        for VM_CONFIG in `find $OPENQRM_VM_DIR/* -name autostart 2>/dev/null`; do
            VM_NAME=`dirname $VM_CONFIG`
            VM_NAME=`basename $VM_NAME`
            echo "- auto-starting VM $VM_NAME"
            $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/lxc-storage/bin/openqrm-lxc-storage-vm start -n $VM_NAME
        done
    fi

}


function openqrm_plugin_lxc_storage_stop() {
	echo "Stopping the openQRM lxc-storage-plugin"
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/lxc-storage/.running
}

function openqrm_plugin_lxc_storage_uninstall() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "lxc-storage: Please give a username to uninstall the plugin : "
		read USERNAME
		echo	
		echo -n "lxc-storage: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Uninstalling the openQRM lxc-storage-plugin"
	openqrm_plugin_lxc_storage_stop
	openqrm_server_remove_deployment_type $USERNAME $PASSWORD lxc-lvm-deployment
	openqrm_server_remove_virtualization_type $USERNAME $PASSWORD lxc-storage
	openqrm_server_remove_virtualization_type $USERNAME $PASSWORD lxc-storage-vm
	# removing the table
	if ! wget -q $WGET_NO_CERT_CHECK -O /dev/null --http-user=$USERNAME --http-password=$PASSWORD "$OPENQRM_WEB_PROTOCOL://$resource_openqrmserver/openqrm/base/plugins/lxc-storage/lxc-storage-action.php?lvm_storage_command=uninstall"; then
		aws_log init "ERROR: Could not drop the lxc-storage-plugin tables in the database!"
		return 1
	fi
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/lxc-storage
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/boot-service-lxc-storage.tgz
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image.lxc-lvm-deployment.php
    # remove the default initrd template + linuxrc
    rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/openqrm-initrd-lxc.tgz

}


function openqrm_plugin_lxc_storage_init() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "lxc-storage: Please give a username to init the plugin : "
		read USERNAME
		echo	
		echo -n "lxc-storage: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Initializing the openQRM lxc-storage-plugin"
	openqrm_server_add_deployment_type $USERNAME $PASSWORD lxc-lvm-deployment lxc-lvm-deployment "LVM deployment for LXC" lxc-storage "LXC LVM Storage"
	openqrm_server_add_virtualization_type $USERNAME $PASSWORD lxc-storage "LXC-Storage Host"
	openqrm_server_add_virtualization_type $USERNAME $PASSWORD lxc-storage-vm "LXC-Storage VM"

	# linking the web dir
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/lxc-storage/web $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/lxc-storage
	# link the boot-service
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/lxc-storage/web/boot-service-lxc-storage.tgz $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/boot-service-lxc-storage.tgz
	# linking the image deployment parameters menu
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/lxc-storage/web/image.lxc-lvm-deployment.php $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image.lxc-lvm-deployment.php
    # create storage dir for stat files
    mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/lxc-storage/web/storage
    chmod 777 $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/lxc-storage/web/storage
    # create lxc-stat dir
    mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/lxc-storage/web/lxc-stat
    chmod -R 777 $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/lxc-storage/web/lxc-stat
    # cp the default initrd template + linuxrc
    /bin/cp -f $OPENQRM_SERVER_BASE_DIR/openqrm/etc/templates/openqrm-initrd-default.tgz $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/openqrm-initrd-lxc.tgz
    chmod 755 $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/openqrm-initrd-lxc.tgz
	# creating the table
	if ! wget -q $WGET_NO_CERT_CHECK -O /dev/null --http-user=$USERNAME --http-password=$PASSWORD "$OPENQRM_WEB_PROTOCOL://$resource_openqrmserver/openqrm/base/plugins/lxc-storage/lxc-storage-action.php?lvm_storage_command=init"; then
		aws_log init "ERROR: Could not create the lxc-storage-plugin tables in the database!"
		return 1
	fi
	
}

USER=$2
PASS=$3

case "$1" in
	start)
		openqrm_plugin_lxc_storage_start
		;;
	stop)
		openqrm_plugin_lxc_storage_stop
		;;
	restart)
		openqrm_plugin_lxc_storage_stop
		sleep 1
		openqrm_plugin_lxc_storage_start
		;;
	init)
		openqrm_plugin_lxc_storage_init $USER $PASS
		;;
	uninstall)
		openqrm_plugin_lxc_storage_uninstall $USER $PASS
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?




