#!/bin/bash
#
# openQRM Enterprise developed by openQRM Enterprise GmbH.
#
# All source code and content (c) Copyright 2012, openQRM Enterprise GmbH unless specifically noted otherwise.
#
# This source code is released under the GNU General Public License version 2, unless otherwise agreed with openQRM Enterprise GmbH.
# The latest version of this license can be found here: src/doc/LICENSE.txt
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://openqrm-enterprise.com
#
# Copyright 2012, openQRM Enterprise GmbH <info@openqrm-enterprise.com>
#


function clean_tap_devs() {
        ALL_TAPS_IN_OVS=`/usr/local/bin/ovs-vsctl list Port | grep name | grep tap | cut -d':' -f2 | cut -d'"' -f2`
        ALL_TAP_DEVICES=`/sbin/ifconfig | grep ^tap`
        for OVS_TAP in $ALL_TAPS_IN_OVS; do
                echo $OVS_TAP
                if echo $ALL_TAP_DEVICES | grep -w $OVS_TAP; then
                        echo "-- $OVS_TAP still active" | logger
                else
                        echo "-- $OVS_TAP done, removing from ovs" | logger
                        OVS_BRIDGE_FOR_TAP=`/usr/local/bin/ovs-vsctl port-to-br $OVS_TAP`
                        /usr/local/bin/ovs-vsctl del-port $OVS_BRIDGE_FOR_TAP $OVS_TAP
                fi
        done
}


echo "-------------- started tapclean" | logger
sleep 5
echo "-------------- running tapclean" | logger
clean_tap_devs

rm -f /tmp/vm.log

