#!/bin/bash
#
# This file is part of openQRM.
#
# openQRM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation.
#
# openQRM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openQRM.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2011, openQRM Enterprise GmbH <info@openqrm-enterprise.com>
#


function clean_tap_devs() {
        ALL_TAPS_IN_OVS=`/usr/local/bin/ovs-vsctl list Port | grep name | grep tap | cut -d':' -f2 | cut -d'"' -f2`
        ALL_TAP_DEVICES=`/sbin/ifconfig | grep ^tap`
        for OVS_TAP in $ALL_TAPS_IN_OVS; do
                echo $OVS_TAP
                if echo $ALL_TAP_DEVICES | grep -w $OVS_TAP; then
                        echo "-- $OVS_TAP still active" | logger
                else
                        echo "-- $OVS_TAP done, removing from ovs" | logger
                        OVS_BRIDGE_FOR_TAP=`/usr/local/bin/ovs-vsctl port-to-br $OVS_TAP`
                        /usr/local/bin/ovs-vsctl del-port $OVS_BRIDGE_FOR_TAP $OVS_TAP
                fi
        done
}


echo "-------------- started tapclean" | logger
sleep 5
echo "-------------- running tapclean" | logger
clean_tap_devs

rm -f /tmp/vm.log

