#!/bin/bash
# this is the functions file for the drbdmc-plugin
#
# This file is part of openQRM.
#
# openQRM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation.
#
# openQRM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openQRM.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2011, Matthias Rechenburg <matt@openqrm.com>
#

DRBDMC_LOCK_FILE=/var/run/drbdmc/drbdmc-plugin.lock
DRBDMC_LOCK_DELAY=5
DRBDMC_LOCK_RETRY=100
DRBDMC_LOCK_TIMEOUT=500


# logs for drbdmc
function drbdmc_log() {
	local COMPONENT=$1
	shift
	local MESSAGE=$@
	logger -i -t "drbdmc plug-in" "$COMPONENT : $MESSAGE"
}

