#!/bin/bash
# init script for the openQRM citrix-storage-plugin
#
# This file is part of openQRM.
#
# openQRM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation.
#
# openQRM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openQRM.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2011, openQRM Enterprise GmbH <info@openqrm-enterprise.com>
#

OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/citrix-storage/include/openqrm-plugin-citrix-storage-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/citrix-storage/etc/openqrm-plugin-citrix-storage.conf
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
openqrm_server_get_config
export LANG=C
export resource_openqrmserver=$OPENQRM_SERVER_IP_ADDRESS


function openqrm_plugin_citrix-storage_check_for_xe() {
	if [ ! -x "$CITRIX_STORAGE_XE_BINARY" ]; then
		echo "openqrm-plugin-citrix-storage" "Xe binary ($CITRIX_STORAGE_XE_BINARY) missing! Could not enable the Citrix-storage plugin"
		echo "Please install the Xe binary (xen-server-tools package) !"
		openqrm_post_event 0 "get" 3 "openqrm-plugin-citrix-storage" "Xe binary ($CITRIX_STORAGE_XE_BINARY) missing! Could not enable the Citrix-storage plugin"
		openqrm_post_event 0 "get" 3 "openqrm-plugin-citrix-storage" "Please install the Xe binary (xen-server-tools package) !"
		exit 1
	fi

}


function openqrm_plugin_citrix-storage_start() {
	echo "Starting the openQRM citrix-storage-plugin"
	openqrm_plugin_citrix-storage_check_for_xe
	touch $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/citrix-storage/.running
}


function openqrm_plugin_citrix-storage_stop() {
	echo "Stopping the openQRM citrix-storage-plugin"
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/citrix-storage/.running
}

function openqrm_plugin_citrix-storage_uninstall() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "citrix-storage: Please give a username to uninstall the plugin : "
		read USERNAME
		echo
		echo -n "citrix-storage: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Uninstalling the openQRM citrix-storage-plugin"
	openqrm_plugin_citrix-storage_stop
	openqrm_server_remove_deployment_type $USERNAME $PASSWORD citrix-deployment
	openqrm_server_remove_virtualization_type $USERNAME $PASSWORD citrix-storage
	openqrm_server_remove_virtualization_type $USERNAME $PASSWORD citrix-storage-vm
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/citrix-storage
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image.citrix-deployment.php
	rm -rf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/citrix-storage/web/citrix-storage-stat

}

function openqrm_plugin_citrix-storage_init() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "citrix-storage: Please give a username to init the plugin : "
		read USERNAME
		echo
		echo -n "citrix-storage: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Initializing the openQRM citrix-storage-plugin"
	openqrm_plugin_citrix-storage_check_for_xe
	# add deployment type
	openqrm_server_add_deployment_type $USERNAME $PASSWORD citrix-deployment citrix-deployment "Local Deployment Citrix" citrix-storage "Citrix Storage"
	# adding virtualization type
	openqrm_server_add_virtualization_type $USERNAME $PASSWORD citrix-storage "Citrix-storage Host"
	openqrm_server_add_virtualization_type $USERNAME $PASSWORD citrix-storage-vm "Citrix-storage VM"
	# linking the web dir
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/citrix-storage/web $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/citrix-storage
	# create dir for stat files
	mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/citrix-storage/web/citrix-storage-stat
	chmod 777 $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/citrix-storage/web/citrix-storage-stat
	# linking the rootdevice identifier hook
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/citrix-storage/web/image.citrix-deployment.php $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image.citrix-deployment.php

}

USER=$2
PASS=$3

case "$1" in
	start)
		openqrm_plugin_citrix-storage_start
		;;
	stop)
		openqrm_plugin_citrix-storage_stop
		;;
	restart)
		openqrm_plugin_citrix-storage_stop
		sleep 1
		openqrm_plugin_citrix-storage_start
		;;
	init)
		openqrm_plugin_citrix-storage_init $USER $PASS
		;;
	uninstall)
		openqrm_plugin_citrix-storage_uninstall $USER $PASS
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?




