#!/bin/bash
# init script for the openQRM drbdmc plugin
#
# This file is part of openQRM.
#
# openQRM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation.
#
# openQRM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openQRM.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2011, Matthias Rechenburg <matt@openqrm.com>
#
OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/drbdmc/include/openqrm-plugin-drbdmc-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/drbdmc/etc/openqrm-plugin-drbdmc.conf

DRBD_MC_VERSION="0.9.7"

function openqrm_plugin_drbdmc_start() {
	echo "Starting the openQRM drbdmc-plugin"
	openqrm_plugin_drbdmc_stop 1>/dev/null 2>&1
	touch $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/drbdmc/.running
	return $RET
}


function openqrm_plugin_drbdmc_stop() {
	echo "Stopping the openQRM drbdmc-plugin"
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/drbdmc/.running
	return 0
}


function openqrm_plugin_drbdmc_init() {
	echo "Initializing the openQRM drbdmc-plugin"
	# copy drbd-applet to the cloud
	mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/cloud/cloud-portal/web/user/drbdmc/
	cd $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/cloud/cloud-portal/web/user/drbdmc/
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/drbdmc/web/drbdmc-gui.php .
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/drbdmc/web/DMC-applet-$DRBD_MC_VERSION.jar .
	cd - 1>/dev/null
	cp -f $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/drbdmc/web/img/plugin.png $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/cloud/cloud-portal/web/img/ha_console.png
	# linking the web dir
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/drbdmc/web $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/drbdmc
	return 0
}


function openqrm_plugin_drbdmc_uninstall() {
	echo "Uninstalling the openQRM drbdmc-plugin"
	openqrm_plugin_drbdmc_stop
	# remove from cloud
	rm -rf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/cloud/cloud-portal/web/user/drbdmc
	rm -f $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/cloud/cloud-portal/web/img/ha_console.png
	# unlinking the web dir
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/drbdmc
}



case "$1" in
	start)
		openqrm_plugin_drbdmc_start
		;;
	stop)
		openqrm_plugin_drbdmc_stop
		;;
	restart)
		openqrm_plugin_drbdmc_stop
		sleep 1
		openqrm_plugin_drbdmc_start
		;;
	init)
		openqrm_plugin_drbdmc_init
		;;
	uninstall)
		openqrm_plugin_drbdmc_uninstall
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?


