#!/bin/bash
# init script for the openQRM idoit plugin
#
# This file is part of openQRM.
#
# openQRM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation.
#
# openQRM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openQRM.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2011, openQRM Enterprise GmbH <info@openqrm-enterprise.com>
#
OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/idoit/include/openqrm-plugin-idoit-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/idoit/etc/openqrm-plugin-idoit.conf

HTPASSWD="htpasswd"
if [ -f /etc/SuSE-release ]; then
	HTPASSWD="htpasswd2"
fi

function openqrm_plugin_idoit_start() {
	echo "Starting the openQRM idoit-plugin"
	touch $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/idoit/.running
	return 0
}


function openqrm_plugin_idoit_stop() {
	echo "Stopping the openQRM idoit-plugin"
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/idoit/.running
	return 0
}


function openqrm_plugin_idoit_init() {
	echo "Initializing the openQRM idoit-plugin"
	# linking the web dir
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/idoit/web $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/idoit
}


function openqrm_plugin_idoit_uninstall() {
	echo "Uninstalling the openQRM idoit-plugin"
	openqrm_plugin_idoit_stop
	rm -rf $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/idoit
}



case "$1" in
	start)
		openqrm_plugin_idoit_start
		;;
	stop)
		openqrm_plugin_idoit_stop
		;;
	restart)
		openqrm_plugin_idoit_stop
		sleep 1
		openqrm_plugin_idoit_start
		;;
	init)
		openqrm_plugin_idoit_init
		;;
	uninstall)
		openqrm_plugin_idoit_uninstall
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?


