#!/bin/bash
# this is the functions file for the collectd-plugin
#
# openQRM Enterprise developed by openQRM Enterprise GmbH.
#
# All source code and content (c) Copyright 2012, openQRM Enterprise GmbH unless specifically noted otherwise.
#
# This source code is released under the GNU General Public License version 2, unless otherwise agreed with openQRM Enterprise GmbH.
# The latest version of this license can be found here: src/doc/LICENSE.txt
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://openqrm-enterprise.com
#
# Copyright 2012, openQRM Enterprise GmbH <info@openqrm-enterprise.com>
#
COLLECTD_MANAGER_LOCK_FILE=/var/run/openqrm/collectd-plugin.lock
COLLECTD_MANAGER_LOCK_DELAY=5
COLLECTD_MANAGER_LOCK_RETRY=100
COLLECTD_MANAGER_LOCK_TIMEOUT=500
################ common collectd functions

# logs for collectd
function collectd_log() {
	local COMPONENT=$1
	shift
	local MESSAGE=$@
	logger -i -t "collectd plug-in" "$COMPONENT : $MESSAGE"
}


# locking function
function collectd_lock() {
	local COMMAND=$1
	local RET=1

	if [ ! -d `dirname $COLLECTD_MANAGER_LOCK_FILE` ]; then
		mkdir -p `dirname $COLLECTD_MANAGER_LOCK_FILE`
	fi
	case "$COMMAND" in
		aquire)
				lockfile -s $COLLECTD_MANAGER_LOCK_DELAY -r $COLLECTD_MANAGER_LOCK_RETRY -l $COLLECTD_MANAGER_LOCK_TIMEOUT $COLLECTD_MANAGER_LOCK_FILE
				RET=$?
				collectd_log collectd_manager_lock "Aquired the lock"
				return $RET
				;;
		release)
				/bin/rm -f $COLLECTD_MANAGER_LOCK_FILE
				RET=$?
				collectd_log collectd_manager_lock "Released the lock"
				return $RET
				;;
		*)
			collectd_log collectd_manager_lock "No such command. Try 'aquire' or 'release'"
			return 1
			;;
	esac
}



################ collectd functions






