#!/bin/sh
#
# Init script for the openQRM client for ESX
#
# chkconfig: 2345 55 25
# description:  openQRM ESX montirod
#
# processname: openqrm-esx-monitord

RETVAL=0
prog="openqrm-esx-monitord"


start()
{
	echo "Starting $prog: "
    if `which screen 2>/dev/null`; then
    	screen -dmS monitord /bin/openqrm-vmware-esx-monitord
    else
        /bin/openqrm-vmware-esx-monitord &
    fi
}

stop()
{
	echo "Stopping $prog: "
}


case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	*)
		echo $"Usage: $0 {start|stop|restart}"
		RETVAL=1
esac
exit $RETVAL
