#!/bin/bash
# init script for the openQRM vmware-esx-plugin
#
# This file is part of openQRM.
#
# openQRM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation.
#
# openQRM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openQRM.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2011, openQRM Enterprise GmbH <info@openqrm-enterprise.com>
#

OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/vmware-esx/include/openqrm-plugin-vmware-esx-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/vmware-esx/etc/openqrm-plugin-vmware-esx.conf
# get the ip config
openqrm_server_get_config
export resource_openqrmserver=$OPENQRM_SERVER_IP_ADDRESS
export LANG=C
# define wget to use with https
if [ "$OPENQRM_WEB_PROTOCOL" == "https" ]; then
	WGET_NO_CERT_CHECK="--no-check-certificate"
fi

function openqrm_plugin_vmware_esx_start() {
	echo "Starting the openQRM vmware-esx-plugin"
	touch $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/vmware-esx/.running
}


function openqrm_plugin_vmware_esx_stop() {
	echo "Stopping the openQRM vmware-esx-plugin"
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/vmware-esx/.running
}

function openqrm_plugin_vmware_esx_uninstall() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "vmware-esx: Please give a username to uninstall the plugin : "
		read USERNAME
		echo
		echo -n "vmware-esx: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Uninstalling the openQRM vmware-esx-plugin"
	openqrm_plugin_vmware_esx_stop
	# removing the table
	if ! wget -q $WGET_NO_CERT_CHECK -O /dev/null --http-user=$USERNAME --http-password=$PASSWORD "$OPENQRM_WEB_PROTOCOL://$resource_openqrmserver/openqrm/base/plugins/vmware-esx/vmware-esx-action.php?vmware_esx_command=uninstall"; then
		vmware_esx_log init "ERROR: Could not drop the vmware-esx plugin tables in the database!"
		return 1
	fi
	openqrm_server_remove_virtualization_type $USERNAME $PASSWORD vmware-esx
	openqrm_server_remove_virtualization_type $USERNAME $PASSWORD vmware-esx-vm
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/vmware-esx
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/action/vmware-esx-integrate.php
}

function openqrm_plugin_vmware_esx_init() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "vmware-esx: Please give a username to init the plugin : "
		read USERNAME
		echo
		echo -n "vmware-esx: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Initializing the openQRM vmware-esx-plugin"
	# linking the web dir
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/vmware-esx/web $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/vmware-esx
	# creating the table
	if ! wget -q $WGET_NO_CERT_CHECK -O /dev/null --http-user=$USERNAME --http-password=$PASSWORD "$OPENQRM_WEB_PROTOCOL://$resource_openqrmserver/openqrm/base/plugins/vmware-esx/vmware-esx-action.php?vmware_esx_command=init"; then
		vmware_esx_log init "ERROR: Could not create the vmware-esx plugin tables in the database!"
		return 1
	fi
	# adding virtualization type
	openqrm_server_add_virtualization_type $USERNAME $PASSWORD vmware-esx "VMware-ESX Host"
	openqrm_server_add_virtualization_type $USERNAME $PASSWORD vmware-esx-vm "VMware-ESX VM"

}

USER=$2
PASS=$3

case "$1" in
	start)
		openqrm_plugin_vmware_esx_start
		;;
	stop)
		openqrm_plugin_vmware_esx_stop
		;;
	restart)
		openqrm_plugin_vmware_esx_stop
		sleep 1
		openqrm_plugin_vmware_esx_start
		;;
	init)
		openqrm_plugin_vmware_esx_init $USER $PASS
		;;
	uninstall)
		openqrm_plugin_vmware_esx_uninstall $USER $PASS
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?




