#!/bin/bash
# this is the functions file for the tmpfs-storage-plugin
#
# openQRM Enterprise developed by openQRM Enterprise GmbH.
#
# All source code and content (c) Copyright 2012, openQRM Enterprise GmbH unless specifically noted otherwise.
#
# This source code is released under the GNU General Public License version 2, unless otherwise agreed with openQRM Enterprise GmbH.
# The latest version of this license can be found here: src/doc/LICENSE.txt
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://openqrm-enterprise.com
#
# Copyright 2012, openQRM Enterprise GmbH <info@openqrm-enterprise.com>
#


# some definitions
DEFAULT_IMAGE_SIZE=5000
TMPFS_MGMT_LOCK_FILE=/var/run/tmpfs-storage/tmpfs-storage-plugin.lock
TMPFS_MGMT_LOCK_DELAY=5
TMPFS_MGMT_LOCK_RETRY=100
TMPFS_MGMT_LOCK_TIMEOUT=500

################ common tmpfs-storage functions

# logs for tmpfs_storage
function tmpfs_storage_log() {
	local COMPONENT=$1
	shift
	local MESSAGE=$@
	logger -i -t "tmpfs-storage plug-in" "$COMPONENT : $MESSAGE"
}


# locking function
function tmpfs_storage_lock() {
	local COMMAND=$1
	local RET=1

	if [ ! -d `dirname $TMPFS_MGMT_LOCK_FILE` ]; then
		mkdir -p `dirname $TMPFS_MGMT_LOCK_FILE`
	fi
	case "$COMMAND" in
		aquire)
				lockfile -s $TMPFS_MGMT_LOCK_DELAY -r $TMPFS_MGMT_LOCK_RETRY -l $TMPFS_MGMT_LOCK_TIMEOUT $TMPFS_MGMT_LOCK_FILE
				RET=$?
				tmpfs_storage_log tmpfs_storage_lock "Aquired the lock"
				return $RET
				;;
		release)
				/bin/rm -f $TMPFS_MGMT_LOCK_FILE
				RET=$?
				tmpfs_storage_log tmpfs_storage_lock "Released the lock"
				return $RET
				;;
		*)
			tmpfs_storage_log tmpfs_storage_lock "No such command. Try 'aquire' or 'release'"
			return 1
			;;	
	esac
}



################ tmpfs-storage functions











