#!/bin/bash
# this is the functions file for the hybrid-cloud-plugin
#
# openQRM Enterprise developed by openQRM Enterprise GmbH.
#
# All source code and content (c) Copyright 2012, openQRM Enterprise GmbH unless specifically noted otherwise.
#
# This source code is released under the GNU General Public License version 2, unless otherwise agreed with openQRM Enterprise GmbH.
# The latest version of this license can be found here: src/doc/LICENSE.txt
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://openqrm-enterprise.com
#
# Copyright 2012, openQRM Enterprise GmbH <info@openqrm-enterprise.com>
#
HYBRID_CLOUD_LOCK_FILE=/var/run/hybrid-cloud/hybrid-cloud-plugin.lock
HYBRID_CLOUD_LOCK_DELAY=5
HYBRID_CLOUD_LOCK_RETRY=100
HYBRID_CLOUD_LOCK_TIMEOUT=500
################ common hybrid-cloud functions

# logs for hybrid-cloud
function hybrid_cloud_log() {
	local COMPONENT=$1
	shift
	local MESSAGE=$@
	logger -i -t "hybrid-cloud plug-in" "$COMPONENT : $MESSAGE"
}


# locking function
function hybrid_cloud_lock() {
	local COMMAND=$1
	local RET=1

	if [ ! -d `dirname $HYBRID_CLOUD_LOCK_FILE` ]; then
		mkdir -p `dirname $HYBRID_CLOUD_LOCK_FILE`
	fi
	case "$COMMAND" in
		aquire)
				lockfile -s $HYBRID_CLOUD_LOCK_DELAY -r $HYBRID_CLOUD_LOCK_RETRY -l $HYBRID_CLOUD_LOCK_TIMEOUT $HYBRID_CLOUD_LOCK_FILE
				RET=$?
				hybrid_cloud_log hybrid_cloud_lock "Aquired the lock"
				return $RET
				;;
		release)
				/bin/rm -f $HYBRID_CLOUD_LOCK_FILE
				RET=$?
				hybrid_cloud_log hybrid_cloud_lock "Released the lock"
				return $RET
				;;
		*)
			hybrid_cloud_log hybrid_cloud_lock "No such command. Try 'aquire' or 'release'"
			return 1
			;;
	esac
}



################ hybrid-cloud functions


