#!/bin/bash
# this is the functions file for the hybrid-cloud-plugin
#
# This file is part of openQRM.
#
# openQRM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation.
#
# openQRM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openQRM.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2011, openQRM Enterprise GmbH <info@openqrm-enterprise.com>
#
HYBRID_CLOUD_LOCK_FILE=/var/run/hybrid-cloud/hybrid-cloud-plugin.lock
HYBRID_CLOUD_LOCK_DELAY=5
HYBRID_CLOUD_LOCK_RETRY=100
HYBRID_CLOUD_LOCK_TIMEOUT=500
################ common hybrid-cloud functions

# logs for hybrid-cloud
function hybrid_cloud_log() {
	local COMPONENT=$1
	shift
	local MESSAGE=$@
	logger -i -t "hybrid-cloud plug-in" "$COMPONENT : $MESSAGE"
}


# locking function
function hybrid_cloud_lock() {
	local COMMAND=$1
	local RET=1

	if [ ! -d `dirname $HYBRID_CLOUD_LOCK_FILE` ]; then
		mkdir -p `dirname $HYBRID_CLOUD_LOCK_FILE`
	fi
	case "$COMMAND" in
		aquire)
				lockfile -s $HYBRID_CLOUD_LOCK_DELAY -r $HYBRID_CLOUD_LOCK_RETRY -l $HYBRID_CLOUD_LOCK_TIMEOUT $HYBRID_CLOUD_LOCK_FILE
				RET=$?
				hybrid_cloud_log hybrid_cloud_lock "Aquired the lock"
				return $RET
				;;
		release)
				/bin/rm -f $HYBRID_CLOUD_LOCK_FILE
				RET=$?
				hybrid_cloud_log hybrid_cloud_lock "Released the lock"
				return $RET
				;;
		*)
			hybrid_cloud_log hybrid_cloud_lock "No such command. Try 'aquire' or 'release'"
			return 1
			;;
	esac
}



################ hybrid-cloud functions


