#!/bin/bash
# this is the functions file for the vmware-esx-plugin
#
# openQRM Enterprise developed by openQRM Enterprise GmbH.
#
# All source code and content (c) Copyright 2012, openQRM Enterprise GmbH unless specifically noted otherwise.
#
# This source code is released under the GNU General Public License version 2, unless otherwise agreed with openQRM Enterprise GmbH.
# The latest version of this license can be found here: src/doc/LICENSE.txt
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://openqrm-enterprise.com
#
# Copyright 2012, openQRM Enterprise GmbH <info@openqrm-enterprise.com>
#
VMWARE_SERVER_LOCK_FILE=/var/run/openqrm/vmware-esx-plugin.lock
VMWARE_SERVER_DISCOVERY_LOCK_FILE=/var/run/openqrm/vmware-esx-discovery.lock
VMWARE_SERVER_LOCK_DELAY=5
VMWARE_SERVER_LOCK_RETRY=100
VMWARE_SERVER_LOCK_TIMEOUT=500

VM_ACTION_POWERON="poweron"
VM_ACTION_POWEROFF="poweroff"
VM_ACTION_SUSPEND="suspend"
VM_ACTION_RESET="reset"
VM_ACTION_REBOOT="reboot"
VM_ACTION_SHUTDOWN="shutdown"
VM_ACTION_STANDBY="standby"

################ common vmware-esx functions

# logs for vmware-esx
function vmware_esx_log() {
	local COMPONENT=$1
	shift
	local MESSAGE=$@
	echo "vmware-esx plug-in" "$COMPONENT : $MESSAGE"
	logger -i -t "vmware-esx plug-in" "$COMPONENT : $MESSAGE"
}


# locking function
function vmware_esx_lock() {
	local COMMAND=$1
	local RET=1

	if [ ! -d `dirname $VMWARE_SERVER_LOCK_FILE` ]; then
		mkdir -p `dirname $VMWARE_SERVER_LOCK_FILE`
	fi
	case "$COMMAND" in
		aquire)
				lockfile -s $VMWARE_SERVER_LOCK_DELAY -r $VMWARE_SERVER_LOCK_RETRY -l $VMWARE_SERVER_LOCK_TIMEOUT $VMWARE_SERVER_LOCK_FILE
				RET=$?
				vmware_esx_log vmware_esx_lock "Aquired the lock"
				return $RET
				;;
		release)
				/bin/rm -f $VMWARE_SERVER_LOCK_FILE
				RET=$?
				vmware_esx_log vmware_esx_lock "Released the lock"
				return $RET
				;;
		*)
			vmware_esx_log vmware_esx_lock "No such command. Try 'aquire' or 'release'"
			return 1
			;;
	esac
}




# locking function
function vmware_esx_discovery_lock() {
	local COMMAND=$1
	local RET=1

	if [ ! -d `dirname $VMWARE_SERVER_DISCOVERY_LOCK_FILE` ]; then
		mkdir -p `dirname $VMWARE_SERVER_DISCOVERY_LOCK_FILE`
	fi
	case "$COMMAND" in
		aquire)
				lockfile -s $VMWARE_SERVER_LOCK_DELAY -r $VMWARE_SERVER_LOCK_RETRY -l $VMWARE_SERVER_LOCK_TIMEOUT $VMWARE_SERVER_DISCOVERY_LOCK_FILE
				RET=$?
				vmware_esx_log vmware_esx_discovery_lock "Aquired the lock"
				return $RET
				;;
		release)
				/bin/rm -f $VMWARE_SERVER_DISCOVERY_LOCK_FILE
				RET=$?
				vmware_esx_log vmware_esx_discovery_lock "Released the lock"
				return $RET
				;;
		*)
			vmware_esx_log vmware_esx_discovery_lock "No such command. Try 'aquire' or 'release'"
			return 1
			;;
	esac
}


################ vmware-esx functions






