#!/bin/bash
#
# openQRM Enterprise developed by openQRM Enterprise GmbH.
#
# All source code and content (c) Copyright 2012, openQRM Enterprise GmbH unless specifically noted otherwise.
#
# This source code is released under the GNU General Public License version 2, unless otherwise agreed with openQRM Enterprise GmbH.
# The latest version of this license can be found here: src/doc/LICENSE.txt
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://openqrm-enterprise.com
#
# Copyright 2012, openQRM Enterprise GmbH <info@openqrm-enterprise.com>

OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/cobbler/include/openqrm-plugin-cobbler-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/cobbler/etc/openqrm-plugin-cobbler.conf
# get the ip config
openqrm_server_get_config
export resource_openqrmserver=$OPENQRM_SERVER_IP_ADDRESS
export LANG=C
# define wget to use with https
if [ "$OPENQRM_WEB_PROTOCOL" == "https" ]; then
	WGET_NO_CERT_CHECK="--no-check-certificate"
fi

function openqrm_plugin_cobbler_start() {
	echo "Starting the openQRM cobbler-plugin"
	touch $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/cobbler/.running
}


function openqrm_plugin_cobbler_stop() {
	echo "Stopping the openQRM cobbler-plugin"
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/cobbler/.running
}

function openqrm_plugin_cobbler_uninstall() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "cobbler: Please give a username to uninstall the plugin : "
		read USERNAME
		echo
		echo -n "cobbler: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Uninstalling the openQRM cobbler-plugin"
	openqrm_plugin_cobbler_stop
	openqrm_server_remove_deployment_type $USERNAME $PASSWORD cobbler-deployment
	# removing the table
	if ! wget -q $WGET_NO_CERT_CHECK -O /dev/null --http-user=$USERNAME --http-password=$PASSWORD "$OPENQRM_WEB_PROTOCOL://$resource_openqrmserver/openqrm/base/plugins/cobbler/cobbler-action.php?cobbler_command=uninstall"; then
		cobbler_log init "ERROR: Could not drop the cobbler-plugin tables in the database!"
		return 1
	fi
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/cobbler
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/boot-service-cobbler.tgz
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image.cobbler-deployment.php
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/template.cobbler-deployment.php
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/openqrm_client_auto_install.snippets
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/openqrm-cobbler-autoinstall-client

}

function openqrm_plugin_cobbler_init() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "cobbler: Please give a username to init the plugin : "
		read USERNAME
		echo
		echo -n "cobbler: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Initializing the openQRM cobbler-plugin"
	openqrm_server_add_deployment_type $USERNAME $PASSWORD cobbler-deployment cobbler-deployment "Automatic Linux Installation (Cobbler)" cobbler "Physical local disk (Cobbler)"
	# linking the web dir
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/cobbler/web $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/cobbler
	# creating the table
	if ! wget -q $WGET_NO_CERT_CHECK -O /dev/null --http-user=$USERNAME --http-password=$PASSWORD "$OPENQRM_WEB_PROTOCOL://$resource_openqrmserver/openqrm/base/plugins/cobbler/cobbler-action.php?cobbler_command=init"; then
		cobbler_log init "ERROR: Could not create the cobbler-plugin tables in the database!"
		rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/cobbler
		return 1
	fi
	# link the boot-service
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/cobbler/web/boot-service-cobbler.tgz $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/boot-service-cobbler.tgz
	# link the image + template hooks
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/cobbler/web/image.cobbler-deployment.php $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image.cobbler-deployment.php
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/cobbler/web/template.cobbler-deployment.php $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/template.cobbler-deployment.php
	# place for the storage stat files
	mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/cobbler/web/storage
	chmod -R 777 $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/cobbler/web/storage
	# creating place for autoinstall files
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/cobbler/bin/openqrm-cobbler-autoinstall-client $OPENQRM_SERVER_BASE_DIR/openqrm/web/boot-service/openqrm-cobbler-autoinstall-client
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/cobbler/etc/templates/openqrm_client_auto_install.snippets $OPENQRM_SERVER_BASE_DIR/openqrm/web/boot-service/openqrm_client_auto_install.snippets

}

USER=$2
PASS=$3

case "$1" in
	start)
		openqrm_plugin_cobbler_start
		;;
	stop)
		openqrm_plugin_cobbler_stop
		;;
	restart)
		openqrm_plugin_cobbler_stop
		sleep 1
		openqrm_plugin_cobbler_start
		;;
	init)
		openqrm_plugin_cobbler_init $USER $PASS
		;;
	uninstall)
		openqrm_plugin_cobbler_uninstall $USER $PASS
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?




