#!/bin/bash
#
# This file is part of openQRM.
#
# openQRM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation.
#
# openQRM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openQRM.  If not, see <http://www.gnu.org/licenses/>.
#
# this is the functions file for the cobbler-plugin
#
# Copyright 2011, openQRM Enterprise GmbH <info@openqrm-enterprise.com>

COBBLER_LOCK_FILE=/var/run/cobbler/cobbler-plugin.lock
COBBLER_LOCK_DELAY=5
COBBLER_LOCK_RETRY=100
COBBLER_LOCK_TIMEOUT=500
################ common cobbler functions

# logs for cobbler
function cobbler_log() {
	local COMPONENT=$1
	shift
	local MESSAGE=$@
	logger -i -t "cobbler plug-in" "$COMPONENT : $MESSAGE"
}


# locking function
function cobbler_lock() {
	local COMMAND=$1
	local RET=1

	if [ ! -d `dirname $COBBLER_LOCK_FILE` ]; then
		mkdir -p `dirname $COBBLER_LOCK_FILE`
	fi
	case "$COMMAND" in
		aquire)
				lockfile -s $COBBLER_LOCK_DELAY -r $COBBLER_LOCK_RETRY -l $COBBLER_LOCK_TIMEOUT $COBBLER_LOCK_FILE
				RET=$?
				cobbler_log cobbler_lock "Aquired the lock"
				return $RET
				;;
		release)
				/bin/rm -f $COBBLER_LOCK_FILE
				RET=$?
				cobbler_log cobbler_lock "Released the lock"
				return $RET
				;;
		*)
			cobbler_log cobbler_lock "No such command. Try 'aquire' or 'release'"
			return 1
			;;
	esac
}



################ cobbler functions


