#!/bin/bash
# openQRM mysql-specfic functions
#
# openQRM Enterprise developed by openQRM Enterprise GmbH.
#
# All source code and content (c) Copyright 2012, openQRM Enterprise GmbH unless specifically noted otherwise.
#
# This source code is released under the GNU General Public License version 2, unless otherwise agreed with openQRM Enterprise GmbH.
# The latest version of this license can be found here: src/doc/LICENSE.txt
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://openqrm-enterprise.com
#
# Copyright 2012, openQRM Enterprise GmbH <info@openqrm-enterprise.com>
#

if [ "$OPENQRM_SERVER_BASE_DIR" == "" ]; then
	echo "ERROR: Please export OPENQRM_SERVER_BASE_DIR before sourcing $0"
	exit 1
fi

. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
# get full server config
openqrm_server_get_config
OPENQRM_DATABASE_INIT="$OPENQRM_SERVER_BASE_DIR/openqrm/etc/db/mysql/openqrm-mysql-init.sql"

OPENQRM_DATABASE_MAINTENANCE="$OPENQRM_SERVER_BASE_DIR/openqrm/etc/db/mysql/openqrm-mysql-maintenance"
OPENQRM_DATABASE_MAINTENANCE_FNAME=`basename $OPENQRM_DATABASE_MAINTENANCE`

if ! which mysql 1>/dev/null 2>&1; then
	echo "ERROR: Mysql client 'mysql' not installed/found on this system"
	exit 1
else
	export MYSQL_CLIENT=`which mysql`
fi
if ! which mysqldump 1>/dev/null 2>&1; then
	echo "ERROR: Mysql 'mysqldump' not installed/found on this system"
	exit 1
else
	export MYSQL_DUMP=`which mysqldump`
fi



function initialize_database() {
	# set the dbname in the sql init-script
	OPENQRM_DATABASE_INIT_TMP=/tmp/openqrm-mysql-init.sql
	cat $OPENQRM_DATABASE_INIT |	\
		sed -e "s/OPENQRM_DB/$OPENQRM_DATABASE_NAME/g" |	\
		sed -e "s/OPENQRM_SERVER_IP_ADDRESS/$OPENQRM_SERVER_IP_ADDRESS/g"	\
		> $OPENQRM_DATABASE_INIT_TMP

	echo "Initializing the openQRM-database"
	if [ -z "$OPENQRM_DATABASE_PASSWORD" ]; then
		$MYSQL_CLIENT -u $OPENQRM_DATABASE_USER --host $OPENQRM_DATABASE_SERVER -e "drop database $OPENQRM_DATABASE_NAME" 1>/dev/null 2>&1
		$MYSQL_CLIENT -u $OPENQRM_DATABASE_USER --host $OPENQRM_DATABASE_SERVER < $OPENQRM_DATABASE_INIT_TMP
		RET=$?
	else
		$MYSQL_CLIENT -u $OPENQRM_DATABASE_USER -p$OPENQRM_DATABASE_PASSWORD --host $OPENQRM_DATABASE_SERVER -e "drop database $OPENQRM_DATABASE_NAME" 1>/dev/null 2>&1
		$MYSQL_CLIENT -u $OPENQRM_DATABASE_USER -p$OPENQRM_DATABASE_PASSWORD --host $OPENQRM_DATABASE_SERVER < $OPENQRM_DATABASE_INIT_TMP
		RET=$?
	fi
	rm -f $OPENQRM_DATABASE_INIT_TMP

	# add the db maintenance to cron
	cat $OPENQRM_DATABASE_MAINTENANCE | sed -e "s#@@OPENQRM_SERVER_BASE_DIR@@#$OPENQRM_SERVER_BASE_DIR#g" > /etc/cron.daily/$OPENQRM_DATABASE_MAINTENANCE_FNAME
	chmod +x /etc/cron.daily/$OPENQRM_DATABASE_MAINTENANCE_FNAME
	if [ -x "/etc/init.d/cron" ]; then
	    if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d cron reload
	    else
		/etc/init.d/cron reload
	    fi
	    elif [ -x "/etc/init.d/crond" ]; then
	    if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d crond reload
	    else
		/etc/init.d/crond reload
	    fi
	else
	    echo "Could not find cron init script in /etc/init.d/. Please reload cron manually!"
	fi
	return $RET
}

function backup_database() {
	local SQL=$1
	echo "Creating backup of the openQRM-database at $SQL"
	if [ -z "$OPENQRM_DATABASE_PASSWORD" ]; then
		$MYSQL_DUMP -u $OPENQRM_DATABASE_USER --host $OPENQRM_DATABASE_SERVER $OPENQRM_DATABASE_NAME > $SQL
		RET=$?
	else
		$MYSQL_DUMP -u $OPENQRM_DATABASE_USER -p$OPENQRM_DATABASE_PASSWORD --host $OPENQRM_DATABASE_SERVER  $OPENQRM_DATABASE_NAME > $SQL
		RET=$?
	fi
	return $RET

}

function restore_database() {
	local SQL=$1
	echo "Restoring the openQRM-database from $SQL"
	if [ -z "$OPENQRM_DATABASE_PASSWORD" ]; then
		$MYSQL_CLIENT -u $OPENQRM_DATABASE_USER --host $OPENQRM_DATABASE_SERVER $OPENQRM_DATABASE_NAME < $SQL
		RET=$?
	else
		$MYSQL_CLIENT -u $OPENQRM_DATABASE_USER -p$OPENQRM_DATABASE_PASSWORD --host $OPENQRM_DATABASE_SERVER $OPENQRM_DATABASE_NAME < $SQL
		RET=$?
	fi
	return $RET

}

function drop_database() {
	echo "Dropping the openQRM-database"
	if [ -z "$OPENQRM_DATABASE_PASSWORD" ]; then
		$MYSQL_CLIENT -u $OPENQRM_DATABASE_USER --host $OPENQRM_DATABASE_SERVER -e "drop database $OPENQRM_DATABASE_NAME" 1>/dev/null 2>&1
		RET=$?
	else
		$MYSQL_CLIENT -u $OPENQRM_DATABASE_USER -p$OPENQRM_DATABASE_PASSWORD --host $OPENQRM_DATABASE_SERVER -e "drop database $OPENQRM_DATABASE_NAME" 1>/dev/null 2>&1
		RET=$?
	fi

	# remove maintenance cron job
	rm -f /etc/cron.daily/$OPENQRM_DATABASE_MAINTENANCE_FNAME
	if [ -x "/etc/init.d/cron" ]; then
	    if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d cron reload
	    else
		/etc/init.d/cron reload
	    fi
	    elif [ -x "/etc/init.d/crond" ]; then
	    if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d crond reload
	    else
		/etc/init.d/crond reload
	    fi
	else
	    echo "Could not find cron init script in /etc/init.d/. Please reload cron manually!"
	fi

	return $RET
}



########################### functions to update the db shema ###########################

function check_table_exists(){
    local DB_TABLE=$1
	if [ -z "$OPENQRM_DATABASE_PASSWORD" ]; then
        $MYSQL_CLIENT -u $OPENQRM_DATABASE_USER --host $OPENQRM_DATABASE_SERVER  $OPENQRM_DATABASE_NAME -e "select * from $DB_TABLE" 1>/dev/null 2>&1
		RET=$?
	else
        $MYSQL_CLIENT -u $OPENQRM_DATABASE_USER -p$OPENQRM_DATABASE_PASSWORD --host $OPENQRM_DATABASE_SERVER  $OPENQRM_DATABASE_NAME -e "select * from $DB_TABLE" 1>/dev/null 2>&1
		RET=$?
	fi
    return $RET
}


function check_column_in_table_exists(){
    local DB_TABLE=$1
    local DB_COLUMN=$2
	if [ -z "$OPENQRM_DATABASE_PASSWORD" ]; then
        $MYSQL_CLIENT -u $OPENQRM_DATABASE_USER --host $OPENQRM_DATABASE_SERVER  $OPENQRM_DATABASE_NAME -e "select $DB_COLUMN from $DB_TABLE" 1>/dev/null 2>&1
		RET=$?
	else
        $MYSQL_CLIENT -u $OPENQRM_DATABASE_USER -p$OPENQRM_DATABASE_PASSWORD --host $OPENQRM_DATABASE_SERVER  $OPENQRM_DATABASE_NAME -e "select $DB_COLUMN from $DB_TABLE" 1>/dev/null 2>&1
		RET=$?
	fi
    return $RET
}


function check_if_data_in_column_of_table_exists(){
    local DB_TABLE=$1
    local DB_COLUMN=$2
    local DB_DATA=$3
    local DB_OUTPUT_LOG="/tmp/dboutput.log"
	if [ -z "$OPENQRM_DATABASE_PASSWORD" ]; then
        $MYSQL_CLIENT -u $OPENQRM_DATABASE_USER --host $OPENQRM_DATABASE_SERVER  $OPENQRM_DATABASE_NAME -e "select * from $DB_TABLE where $DB_COLUMN=$DB_DATA" > $DB_OUTPUT_LOG
		RET=$?
	else
        $MYSQL_CLIENT -u $OPENQRM_DATABASE_USER -p$OPENQRM_DATABASE_PASSWORD --host $OPENQRM_DATABASE_SERVER  $OPENQRM_DATABASE_NAME -e "select * from $DB_TABLE where $DB_COLUMN=$DB_DATA" > $DB_OUTPUT_LOG
		RET=$?
	fi
    DB_OUTPUT=`cat $DB_OUTPUT_LOG`
    if [ "$RET" == 0 ]; then
        if [ "$DB_OUTPUT" == "" ]; then
            return 1
        else
            return 0
        fi
    else
        return $RET
    fi
}



function run_sql(){
    local DB_SQL=$@
	if [ -z "$OPENQRM_DATABASE_PASSWORD" ]; then
        $MYSQL_CLIENT -u $OPENQRM_DATABASE_USER --host $OPENQRM_DATABASE_SERVER  $OPENQRM_DATABASE_NAME -e "$DB_SQL" 1>/dev/null 2>&1
		RET=$?
	else
        $MYSQL_CLIENT -u $OPENQRM_DATABASE_USER -p$OPENQRM_DATABASE_PASSWORD --host $OPENQRM_DATABASE_SERVER  $OPENQRM_DATABASE_NAME -e "$DB_SQL" 1>/dev/null 2>&1
		RET=$?
	fi
    return $RET
}




function db_update()  {

    # this function applies needed updates to the db-shema if needed in an idempotent way
	if [ -f "$OPENQRM_SERVER_BASE_DIR/openqrm_pre_update/etc/openqrm-server.conf" ]; then
		# for update we have to source the old configuration
		. $OPENQRM_SERVER_BASE_DIR/openqrm_pre_update/etc/openqrm-server.conf
	else
		. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
	fi

    # from 4.6 to 4.7 the following db changes are needed
    # 1  > ALTER TABLE cloud_users ADD cu_cg_id int(5);
    # 2  > create table cloud_usergroups(cg_id INT(5), cg_name VARCHAR(50), cg_role_id INT(5), cg_description VARCHAR(255));
    # 3  > insert into cloud_config(cc_id, cc_key, cc_value) values (25, 'resource_pooling', 'true');
    # 4  > insert into cloud_config(cc_id, cc_key, cc_value) values (26, 'ip-management', 'true');
    # 5  > update cloud_users set cu_cg_id=0;
    # 6  > insert into `cloud_usergroups` VALUES (0,'Default',0,'The default CloudUser Group');
    # 7  > create table cloud_respool(rp_id INT(5), rp_resource_id INT(5), rp_cg_id INT(5));
    # 8  > create table cloud_hostlimit(hl_id INT(5), hl_resource_id INT(5), hl_current_vms INT(5), hl_max_vms INT(5));
    # 9  > create table cloud_power_saver(ps_id INT(5), ps_frequence VARCHAR(50), ps_last_check VARCHAR(50));
    # 10 > insert into `cloud_power_saver` VALUES (0,'1800','');
    # 11 > ALTER TABLE cloud_requests ADD cr_ip_mgmt VARCHAR(255);
    # 12 > create table cloud_profiles(pr_id INT(5), pr_request_time VARCHAR(20), pr_cu_id INT(5), pr_status INT(5), pr_request_time VARCHAR(20), pr_start VARCHAR(20), pr_stop VARCHAR(20), pr_kernel_id INT(5), pr_image_id INT(5), pr_ram_req VARCHAR(20), pr_cpu_req VARCHAR(20), pr_disk_req VARCHAR(20), pr_network_req VARCHAR(255), pr_resource_quantity INT(5), pr_resource_type_req VARCHAR(20), pr_deployment_type_req VARCHAR(50), pr_ha_req VARCHAR(5), pr_shared_req VARCHAR(5), pr_appliance_id VARCHAR(255), pr_puppet_groups VARCHAR(255), pr_ip_mgmt VARCHAR(255), pr_lastbill VARCHAR(20), pr_description VARCHAR(255));
    # 13 > create table cloud_icons(ic_id INT(5), ic_cu_id INT(5), ic_type INT(5), ic_object_id INT(5), ic_filename VARCHAR(255));
    # 14 > create table cloud_matrix(cm_id INT(5), cm_cu_id INT(5), cm_description VARCHAR(255), cm_row01 VARCHAR(255), cm_row02 VARCHAR(255), cm_row03 VARCHAR(255), cm_row04 VARCHAR(255), cm_row05 VARCHAR(255), cm_row06 VARCHAR(255), cm_row07 VARCHAR(255), cm_row08 VARCHAR(255), cm_row09 VARCHAR(255), cm_row10 VARCHAR(255), cm_row11 VARCHAR(255), cm_row12 VARCHAR(255));
    # 15 > create table cloud_matrix_object(mo_id INT(5), mo_pr_id INT(5), mo_cr_id INT(5), mo_ca_id INT(5), mo_ne_id INT(5), mo_table INT(5), mo_x INT(5), mo_y INT(5), mo_state INT(5));
    # 16 > create table cloud_create_vm_lc(vc_id INT(5), vc_resource_id INT(5), vc_cr_id INT(5), vc_cr_resource_number INT(5), vc_request_time VARCHAR(20), vc_vm_create_timeout INT(5), vc_state INT(5));
    # 17 > create table auth_blocker_info(ab_id INT(5) NOT NULL PRIMARY KEY, ab_image_id INT(5), ab_image_name VARCHAR(50),	ab_start_time VARCHAR(20));
    # 18 > insert into cloud_config(cc_id, cc_key, cc_value) values (27, 'max-parallel-phase-one-actions', '0');
    # 19 > insert into cloud_config(cc_id, cc_key, cc_value) values (28, 'max-parallel-phase-two-actions', '3');
    # 20 > insert into cloud_config(cc_id, cc_key, cc_value) values (29, 'max-parallel-phase-three-actions', '0');
    # 21 > insert into cloud_config(cc_id, cc_key, cc_value) values (30, 'max-parallel-phase-four-actions', '0');
    # 22 > insert into cloud_config(cc_id, cc_key, cc_value) values (31, 'max-parallel-phase-five-actions', '0');
    # 23 > insert into cloud_config(cc_id, cc_key, cc_value) values (32, 'max-parallel-phase-six-actions', '0');
    # 24 > insert into cloud_config(cc_id, cc_key, cc_value) values (33, 'max-parallel-phase-seven-actions', '0');
    # 25 > ALTER TABLE event_info MODIFY event_description VARCHAR(255);


    #---------------------------------------------------------------------------
    # from 4.7 to 4.8 the following db changes are needed
        # 1  > ALTER TABLE kernel_info ADD kernel_comment VARCHAR(255);
	# 2  > ALTER TABLE user_info ADD user_lang VARCHAR(5);

    #---------------------------------------------------------------------------
    # from 4.8 to 4.9 the following db changes are needed
	# 1  > ALTER TABLE image_info ADD image_isactive INT(1);
	# 2  > ALTER TABLE cloud_private_image ADD co_clone_on_deploy SMALLINT
	# 3  > ALTER TABLE cloud_requests ADD cr_appliance_hostname VARCHAR(255)
	# 4  > ALTER TABLE cloud_profiles ADD pr_appliance_hostname VARCHAR(255)
	# 5 > insert into cloud_config(cc_id, cc_key, cc_value) values (34, 'appliance_hostname', 'true')";
	# 6 > insert into cloud_config(cc_id, cc_key, cc_value) values (35, 'cloud_zones_client', 'false';
	# 7 > insert into cloud_config(cc_id, cc_key, cc_value) values (36, 'cloud_zones_master_ip', '';
	# 8 > create table cloud_transaction_failed(tf_id BIGINT, tf_ct_id BIGINT);
	# 9 > insert into cloud_config(cc_id, cc_key, cc_value) values (37, 'cloud_external_ip', '');

    #---------------------------------------------------------------------------
    # from 4.9 to 5.0 the following db changes are needed
    #---------------------------------------------------------------------------
	# 1  > ALTER TABLE cloud_users ADD cu_lang VARCHAR(4);
	# 2  > UPDATE user_info set user_lang = 'en';
	# 3  > ALTER TABLE user_info ADD user_wizard_name VARCHAR(255) AFTER user_capabilities;
	# 4  > ALTER TABLE user_info ADD user_wizard_step INT(5) AFTER user_wizard_name;
	# 5  > ALTER TABLE user_info ADD user_wizard_id INT(5) AFTER user_wizard_step;
	# 6  > ALTER TABLE appliance_info ADD appliance_wizard VARCHAR(255) AFTER appliance_comment;
	# 7  > ALTER TABLE appliance_info MODIFY appliance_cpumodel VARCHAR(255);
	# 8  > ALTER TABLE resource_info MODIFY resource_cpumodel VARCHAR(255);
	# 9  > ALTER TABLE cloud_config MODIFY cc_value VARCHAR(255);
	# 10 > ALTER TABLE event_info MODIFY event_id BIGINT;
	# 11 > insert into cloud_config(cc_id, cc_key, cc_value) values (38, 'deprovision_warning', '100');
	# 12 > insert into cloud_config(cc_id, cc_key, cc_value) values (39, 'deprovision_pause', '50')

    echo "- Checking database shema ..."
    echo " - version 4.6 to 4.7"
    # from 4.6 to 4.7 we only have updates in the cloud tables
    # so we check first if the cloud plugin is enabled before appling any changes
    # if cloud enabled .....
    if [ -e "$OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/cloud" ]; then

        # 1  > ALTER TABLE cloud_users ADD cu_cg_id int(5);
        if check_table_exists cloud_users; then
            if ! check_column_in_table_exists cloud_users cu_cg_id; then
                echo " -- db change : ALTER TABLE cloud_users ADD cu_cg_id int(5);"
                run_sql "ALTER TABLE cloud_users ADD cu_cg_id int(5);"
        # 5  > update cloud_users set cu_cg_id=0;
                echo " -- db change : update cloud_users set cu_cg_id=0;"
                run_sql "update cloud_users set cu_cg_id=0;"
            fi
        fi
        # 2  > create table cloud_usergroups(cg_id INT(5), cg_name VARCHAR(50), cg_role_id INT(5), cg_description VARCHAR(255));
        if ! check_table_exists cloud_usergroups; then
            echo " -- db change : create table cloud_usergroups(cg_id INT(5), cg_name VARCHAR(50), cg_role_id INT(5), cg_description VARCHAR(255));"
            run_sql "create table cloud_usergroups(cg_id INT(5), cg_name VARCHAR(50), cg_role_id INT(5), cg_description VARCHAR(255));"
        # 6  > insert into `cloud_usergroups` VALUES (0,'Default',0,'The default CloudUser Group');
            echo " -- db change : insert into cloud_usergroups VALUES (0,'Default',0,'The default CloudUser Group');"
            run_sql "insert into cloud_usergroups VALUES (0,'Default',0,'The default CloudUser Group');"
        fi
        # 3  > insert into cloud_config(cc_id, cc_key, cc_value) values (25, 'resource_pooling', 'true');
        if check_table_exists cloud_config; then
            if ! check_if_data_in_column_of_table_exists cloud_config cc_id 25; then
                echo " -- db change : insert into cloud_config(cc_id, cc_key, cc_value) values (25, 'resource_pooling', 'true');"
                run_sql "insert into cloud_config(cc_id, cc_key, cc_value) values (25, 'resource_pooling', 'true');"
            fi
        fi
        # 4  > insert into cloud_config(cc_id, cc_key, cc_value) values (26, 'ip-management', 'true');
        if check_table_exists cloud_config; then
            if ! check_if_data_in_column_of_table_exists cloud_config cc_id 26; then
                echo " -- db change : insert into cloud_config(cc_id, cc_key, cc_value) values (26, 'ip-management', 'true');"
                run_sql "insert into cloud_config(cc_id, cc_key, cc_value) values (26, 'ip-management', 'true');"
            fi
        fi
        # 18 > insert into cloud_config(cc_id, cc_key, cc_value) values (27, 'max-parallel-phase-one-actions', '0');
        if check_table_exists cloud_config; then
            if ! check_if_data_in_column_of_table_exists cloud_config cc_id 27; then
                echo " -- db change : insert into cloud_config(cc_id, cc_key, cc_value) values (27, 'max-parallel-phase-one-actions', '0');"
                run_sql "insert into cloud_config(cc_id, cc_key, cc_value) values (27, 'max-parallel-phase-one-actions', '0');"
            fi
        fi
        # 19 > insert into cloud_config(cc_id, cc_key, cc_value) values (28, 'max-parallel-phase-two-actions', '3');
        if check_table_exists cloud_config; then
            if ! check_if_data_in_column_of_table_exists cloud_config cc_id 28; then
                echo " -- db change : insert into cloud_config(cc_id, cc_key, cc_value) values (28, 'max-parallel-phase-two-actions', '3');"
                run_sql "insert into cloud_config(cc_id, cc_key, cc_value) values (28, 'max-parallel-phase-two-actions', '3');"
            fi
        fi
        # 20 > insert into cloud_config(cc_id, cc_key, cc_value) values (29, 'max-parallel-phase-three-actions', '0');
        if check_table_exists cloud_config; then
            if ! check_if_data_in_column_of_table_exists cloud_config cc_id 29; then
                echo " -- db change : insert into cloud_config(cc_id, cc_key, cc_value) values (29, 'max-parallel-phase-three-actions', '0');"
                run_sql "insert into cloud_config(cc_id, cc_key, cc_value) values (29, 'max-parallel-phase-three-actions', '0');"
            fi
        fi
        # 21 > insert into cloud_config(cc_id, cc_key, cc_value) values (30, 'max-parallel-phase-four-actions', '0');
        if check_table_exists cloud_config; then
            if ! check_if_data_in_column_of_table_exists cloud_config cc_id 30; then
                echo " -- db change : insert into cloud_config(cc_id, cc_key, cc_value) values (30, 'max-parallel-phase-four-actions', '0');"
                run_sql "insert into cloud_config(cc_id, cc_key, cc_value) values (30, 'max-parallel-phase-four-actions', '0');"
            fi
        fi
        # 22 > insert into cloud_config(cc_id, cc_key, cc_value) values (31, 'max-parallel-phase-five-actions', '0');
        if check_table_exists cloud_config; then
            if ! check_if_data_in_column_of_table_exists cloud_config cc_id 31; then
                echo " -- db change : insert into cloud_config(cc_id, cc_key, cc_value) values (31, 'max-parallel-phase-five-actions', '0');"
                run_sql "insert into cloud_config(cc_id, cc_key, cc_value) values (31, 'max-parallel-phase-five-actions', '0');"
            fi
        fi
        # 23 > insert into cloud_config(cc_id, cc_key, cc_value) values (32, 'max-parallel-phase-six-actions', '0');
        if check_table_exists cloud_config; then
            if ! check_if_data_in_column_of_table_exists cloud_config cc_id 32; then
                echo " -- db change : insert into cloud_config(cc_id, cc_key, cc_value) values (32, 'max-parallel-phase-six-actions', '0');"
                run_sql "insert into cloud_config(cc_id, cc_key, cc_value) values (32, 'max-parallel-phase-six-actions', '0');"
            fi
        fi
        # 24 > insert into cloud_config(cc_id, cc_key, cc_value) values (33, 'max-parallel-phase-seven-actions', '0');
        if check_table_exists cloud_config; then
            if ! check_if_data_in_column_of_table_exists cloud_config cc_id 33; then
                echo " -- db change : insert into cloud_config(cc_id, cc_key, cc_value) values (33, 'max-parallel-phase-seven-actions', '0');"
                run_sql "insert into cloud_config(cc_id, cc_key, cc_value) values (33, 'max-parallel-phase-seven-actions', '0');"
            fi
        fi
        # 5 see 1
        # 6 see 2
        # 7  > create table cloud_respool(rp_id INT(5), rp_resource_id INT(5), rp_cg_id INT(5));
        if ! check_table_exists cloud_respool; then
            echo " -- db change : create table cloud_respool(rp_id INT(5), rp_resource_id INT(5), rp_cg_id INT(5));"
            run_sql "create table cloud_respool(rp_id INT(5), rp_resource_id INT(5), rp_cg_id INT(5));"
        fi
        # 8  > create table cloud_hostlimit(hl_id INT(5), hl_resource_id INT(5), hl_current_vms INT(5), hl_max_vms INT(5));
        if ! check_table_exists cloud_hostlimit; then
            echo " -- db change : create table cloud_hostlimit(hl_id INT(5), hl_resource_id INT(5), hl_current_vms INT(5), hl_max_vms INT(5));"
            run_sql "create table cloud_hostlimit(hl_id INT(5), hl_resource_id INT(5), hl_current_vms INT(5), hl_max_vms INT(5));"
        fi
        # 9  > create table cloud_power_saver(ps_id INT(5), ps_frequence VARCHAR(50), ps_last_check VARCHAR(50));
        if ! check_table_exists cloud_power_saver; then
            echo " -- db change : create table cloud_power_saver(ps_id INT(5), ps_frequence VARCHAR(50), ps_last_check VARCHAR(50));"
            run_sql "create table cloud_power_saver(ps_id INT(5), ps_frequence VARCHAR(50), ps_last_check VARCHAR(50));"
        # 10 > insert into cloud_power_saver VALUES (0,'1800','');
            echo " -- db change : insert into cloud_power_saver VALUES (0,'1800','');"
            run_sql "insert into cloud_power_saver VALUES (0,'1800','');"
        fi
    fi
    # 11 > ALTER TABLE cloud_requests ADD cr_ip_mgmt VARCHAR(255);
    if check_table_exists cloud_requests; then
        if ! check_column_in_table_exists cloud_requests cr_ip_mgmt; then
            echo " -- db change : ALTER TABLE cloud_requests ADD cr_ip_mgmt VARCHAR(255);"
            run_sql "ALTER TABLE cloud_requests ADD cr_ip_mgmt VARCHAR(255);"
        fi
    fi
    # 12 > create table cloud_profiles(pr_id INT(5), pr_name VARCHAR(20), pr_cu_id INT(5), pr_status INT(5), pr_request_time VARCHAR(20), pr_start VARCHAR(20), pr_stop VARCHAR(20), pr_kernel_id INT(5), pr_image_id INT(5), pr_ram_req VARCHAR(20), pr_cpu_req VARCHAR(20), pr_disk_req VARCHAR(20), pr_network_req VARCHAR(255), pr_resource_quantity INT(5), pr_resource_type_req VARCHAR(20), pr_deployment_type_req VARCHAR(50), pr_ha_req VARCHAR(5), pr_shared_req VARCHAR(5), pr_appliance_id VARCHAR(255), pr_puppet_groups VARCHAR(255), pr_ip_mgmt VARCHAR(255), pr_lastbill VARCHAR(20), pr_description VARCHAR(255));
    if ! check_table_exists cloud_profiles; then
        echo " -- db change : create table cloud_profiles(pr_id INT(5), pr_name VARCHAR(20), pr_cu_id INT(5), pr_status INT(5), pr_request_time VARCHAR(20), pr_start VARCHAR(20), pr_stop VARCHAR(20), pr_kernel_id INT(5), pr_image_id INT(5), pr_ram_req VARCHAR(20), pr_cpu_req VARCHAR(20), pr_disk_req VARCHAR(20), pr_network_req VARCHAR(255), pr_resource_quantity INT(5), pr_resource_type_req VARCHAR(20), pr_deployment_type_req VARCHAR(50), pr_ha_req VARCHAR(5), pr_shared_req VARCHAR(5), pr_appliance_id VARCHAR(255), pr_puppet_groups VARCHAR(255), pr_ip_mgmt VARCHAR(255), pr_lastbill VARCHAR(20), pr_description VARCHAR(255));"
        run_sql "create table cloud_profiles(pr_id INT(5), pr_name VARCHAR(20), pr_cu_id INT(5), pr_status INT(5), pr_request_time VARCHAR(20), pr_start VARCHAR(20), pr_stop VARCHAR(20), pr_kernel_id INT(5), pr_image_id INT(5), pr_ram_req VARCHAR(20), pr_cpu_req VARCHAR(20), pr_disk_req VARCHAR(20), pr_network_req VARCHAR(255), pr_resource_quantity INT(5), pr_resource_type_req VARCHAR(20), pr_deployment_type_req VARCHAR(50), pr_ha_req VARCHAR(5), pr_shared_req VARCHAR(5), pr_appliance_id VARCHAR(255), pr_puppet_groups VARCHAR(255), pr_ip_mgmt VARCHAR(255), pr_lastbill VARCHAR(20), pr_description VARCHAR(255));"
    fi
    # 13 > create table cloud_icons(ic_id INT(5), ic_cu_id INT(5), ic_type INT(5), ic_object_id INT(5), ic_filename VARCHAR(255));
    if ! check_table_exists cloud_icons; then
        echo " -- db change : create table cloud_icons(ic_id INT(5), ic_cu_id INT(5), ic_type INT(5), ic_object_id INT(5), ic_filename VARCHAR(255));"
        run_sql "create table cloud_icons(ic_id INT(5), ic_cu_id INT(5), ic_type INT(5), ic_object_id INT(5), ic_filename VARCHAR(255));"
    fi
    # 14 > create table cloud_matrix(cm_id INT(5), cm_cu_id INT(5), cm_description VARCHAR(255), cm_row01 VARCHAR(255), cm_row02 VARCHAR(255), cm_row03 VARCHAR(255), cm_row04 VARCHAR(255), cm_row05 VARCHAR(255), cm_row06 VARCHAR(255), cm_row07 VARCHAR(255), cm_row08 VARCHAR(255), cm_row09 VARCHAR(255), cm_row10 VARCHAR(255), cm_row11 VARCHAR(255), cm_row12 VARCHAR(255));
    if ! check_table_exists cloud_matrix; then
        echo " -- db change : create table cloud_matrix(cm_id INT(5), cm_cu_id INT(5), cm_description VARCHAR(255), cm_row01 VARCHAR(255), cm_row02 VARCHAR(255), cm_row03 VARCHAR(255), cm_row04 VARCHAR(255), cm_row05 VARCHAR(255), cm_row06 VARCHAR(255), cm_row07 VARCHAR(255), cm_row08 VARCHAR(255), cm_row09 VARCHAR(255), cm_row10 VARCHAR(255), cm_row11 VARCHAR(255), cm_row12 VARCHAR(255));"
        run_sql "create table cloud_matrix(cm_id INT(5), cm_cu_id INT(5), cm_description VARCHAR(255), cm_row01 VARCHAR(255), cm_row02 VARCHAR(255), cm_row03 VARCHAR(255), cm_row04 VARCHAR(255), cm_row05 VARCHAR(255), cm_row06 VARCHAR(255), cm_row07 VARCHAR(255), cm_row08 VARCHAR(255), cm_row09 VARCHAR(255), cm_row10 VARCHAR(255), cm_row11 VARCHAR(255), cm_row12 VARCHAR(255));"
    fi
    # 15 > create table cloud_matrix_object(mo_id INT(5), mo_pr_id INT(5), mo_cr_id INT(5), mo_ca_id INT(5), mo_ne_id INT(5), mo_table INT(5), mo_x INT(5), mo_y INT(5), mo_state INT(5));
    if ! check_table_exists cloud_matrix_object; then
        echo " -- db change : create table cloud_matrix_object(mo_id INT(5), mo_pr_id INT(5), mo_cr_id INT(5), mo_ca_id INT(5), mo_ne_id INT(5), mo_table INT(5), mo_x INT(5), mo_y INT(5), mo_state INT(5));"
        run_sql "create table cloud_matrix_object(mo_id INT(5), mo_pr_id INT(5), mo_cr_id INT(5), mo_ca_id INT(5), mo_ne_id INT(5), mo_table INT(5), mo_x INT(5), mo_y INT(5), mo_state INT(5));"
    fi
    # 16 > create table cloud_create_vm_lc(vc_id INT(5), vc_resource_id INT(5), vc_cr_id INT(5), vc_cr_resource_number INT(5), vc_request_time VARCHAR(20), vc_vm_create_timeout INT(5), vc_state INT(5));
    if ! check_table_exists cloud_create_vm_lc; then
        echo " -- db change : create table cloud_create_vm_lc(vc_id INT(5), vc_resource_id INT(5), vc_cr_id INT(5), vc_cr_resource_number INT(5), vc_request_time VARCHAR(20), vc_vm_create_timeout INT(5), vc_state INT(5));"
        run_sql "create table cloud_create_vm_lc(vc_id INT(5), vc_resource_id INT(5), vc_cr_id INT(5), vc_cr_resource_number INT(5), vc_request_time VARCHAR(20), vc_vm_create_timeout INT(5), vc_state INT(5));"
    fi
    # 17 > create table auth_blocker_info(ab_id INT(5) NOT NULL PRIMARY KEY, ab_image_id INT(5), ab_image_name VARCHAR(50), ab_start_time VARCHAR(20));
    if ! check_table_exists auth_blocker_info; then
        echo " -- db change : create table auth_blocker_info(ab_id INT(5) NOT NULL PRIMARY KEY, ab_image_id INT(5), ab_image_name VARCHAR(50), ab_start_time VARCHAR(20));"
        run_sql "create table auth_blocker_info(ab_id INT(5) NOT NULL PRIMARY KEY, ab_image_id INT(5), ab_image_name VARCHAR(50), ab_start_time VARCHAR(20));"
    fi
    # 18 - 24 see cloud sections
    # 25 > ALTER TABLE event_info MODIFY event_description VARCHAR(255);
    echo " -- db change : ALTER TABLE event_info MODIFY event_description VARCHAR(255);"
    run_sql "ALTER TABLE event_info MODIFY event_description VARCHAR(255);"


    echo "- Database sanity check for version 4.6 to 4.7 finished"

    # 1  > ALTER TABLE kernel_info ADD kernel_comment VARCHAR(255);
	if ! check_column_in_table_exists kernel_info kernel_comment; then
		echo " -- db change : ALTER TABLE kernel_info ADD kernel_comment VARCHAR(255)"
		run_sql "ALTER TABLE kernel_info ADD kernel_comment VARCHAR(255);"
	fi
    # 2 > ALTER TABLE user_info ADD user_lang VARCHAR(5);
    if check_table_exists user_info; then
        if ! check_column_in_table_exists user_info user_lang; then
            echo " -- db change : ALTER TABLE user_info ADD user_lang VARCHAR(5);"
            run_sql "ALTER TABLE user_info ADD user_lang VARCHAR(5);"
        fi
    fi
    echo "- Database sanity check for version 4.7 to 4.8 finished"


    # 1  > ALTER TABLE image_info ADD image_isactive INT(1);
	if ! check_column_in_table_exists image_info image_isactive; then
		echo " -- db change : ALTER TABLE image_info ADD image_isactive INT(1)"
		run_sql "ALTER TABLE image_info ADD image_isactive INT(1);"
	fi

    # if cloud enabled .....
    if [ -e "$OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/cloud" ]; then

		# 2  > ALTER TABLE image_info ADD image_isactive SMALLINT;
		if ! check_column_in_table_exists cloud_private_image co_clone_on_deploy; then
			echo " -- db change : ALTER TABLE cloud_private_image ADD co_clone_on_deploy SMALLINT"
			run_sql "ALTER TABLE cloud_private_image ADD co_clone_on_deploy SMALLINT;"
		fi
		# 3  > ALTER TABLE cloud_requests ADD cr_appliance_hostname VARCHAR(255)
		if ! check_column_in_table_exists cloud_requests cr_appliance_hostname; then
			echo " -- db change : ALTER TABLE cloud_requests ADD cr_appliance_hostname VARCHAR(255)"
			run_sql "ALTER TABLE cloud_requests ADD cr_appliance_hostname VARCHAR(255);"
		fi
		# 4  > ALTER TABLE cloud_profiles ADD pr_appliance_hostname VARCHAR(255)
		if ! check_column_in_table_exists cloud_profiles pr_appliance_hostname; then
			echo " -- db change : ALTER TABLE cloud_profiles ADD pr_appliance_hostname VARCHAR(255)"
			run_sql "ALTER TABLE cloud_profiles ADD pr_appliance_hostname VARCHAR(255);"
		fi
        # 5 > insert into cloud_config(cc_id, cc_key, cc_value) values (34, 'appliance_hostname', 'true')";
        if check_table_exists cloud_config; then
            if ! check_if_data_in_column_of_table_exists cloud_config cc_id 34; then
                echo " -- db change : insert into cloud_config(cc_id, cc_key, cc_value) values (34, 'appliance_hostname', 'true')"
                run_sql "insert into cloud_config(cc_id, cc_key, cc_value) values (34, 'appliance_hostname', 'true');"
            fi
        fi
		# 6 > insert into cloud_config(cc_id, cc_key, cc_value) values (35, 'cloud_zones_client', 'false');
        if check_table_exists cloud_config; then
            if ! check_if_data_in_column_of_table_exists cloud_config cc_id 35; then
                echo " -- db change : insert into cloud_config(cc_id, cc_key, cc_value) values (35, 'cloud_zones_client', 'false')"
                run_sql "insert into cloud_config(cc_id, cc_key, cc_value) values (35, 'cloud_zones_client', 'false');"
            fi
        fi
		# 7 > insert into cloud_config(cc_id, cc_key, cc_value) values (36, 'cloud_zones_master_ip', '');
        if check_table_exists cloud_config; then
            if ! check_if_data_in_column_of_table_exists cloud_config cc_id 36; then
                echo " -- db change : insert into cloud_config(cc_id, cc_key, cc_value) values (36, 'cloud_zones_master_ip', '')"
                run_sql "insert into cloud_config(cc_id, cc_key, cc_value) values (36, 'cloud_zones_master_ip', '');"
            fi
        fi
		# 8 > create table cloud_transaction_failed(tf_id BIGINT, tf_ct_id BIGINT);
		if ! check_table_exists cloud_transaction_failed; then
			echo " -- db change : create table cloud_transaction_failed(tf_id BIGINT, tf_ct_id BIGINT);"
			run_sql "create table cloud_transaction_failed(tf_id BIGINT, tf_ct_id BIGINT);"
		fi
		# 9 > insert into cloud_config(cc_id, cc_key, cc_value) values (37, 'cloud_external_ip', '')
        if check_table_exists cloud_config; then
            if ! check_if_data_in_column_of_table_exists cloud_config cc_id 37; then
                echo " -- db change : insert into cloud_config(cc_id, cc_key, cc_value) values (37, 'cloud_external_ip', '')"
                run_sql "insert into cloud_config(cc_id, cc_key, cc_value) values (37, 'cloud_external_ip', '');"
            fi
        fi


	fi

    echo "- Database sanity check for version 4.8 to 4.9 finished"

    # if cloud enabled .....
    if [ -e "$OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/cloud" ]; then

		# 1  > ALTER TABLE cloud_users ADD cu_lang VARCHAR(4);
		if ! check_column_in_table_exists cloud_users cu_lang; then
			echo " -- db change : ALTER TABLE cloud_users ADD cu_lang VARCHAR(4)"
			run_sql "ALTER TABLE cloud_users ADD cu_lang VARCHAR(4);"
		fi
		# 9  > ALTER TABLE cloud_config MODIFY cc_value VARCHAR(255);
		echo " -- db change : ALTER TABLE cloud_config MODIFY cc_value VARCHAR(255)"
		run_sql "ALTER TABLE cloud_config MODIFY cc_value VARCHAR(255);"

		# 11  > insert into cloud_config(cc_id, cc_key, cc_value) values (38, 'deprovision_warning', '100');
        if check_table_exists cloud_config; then
            if ! check_if_data_in_column_of_table_exists cloud_config cc_id 38; then
                echo " -- db change : insert into cloud_config(cc_id, cc_key, cc_value) values (38, 'deprovision_warning', '100')"
                run_sql "insert into cloud_config(cc_id, cc_key, cc_value) values (38, 'deprovision_warning', '100');"
            fi
        fi

		# 12  > insert into cloud_config(cc_id, cc_key, cc_value) values (39, 'deprovision_pause', '50')
        if check_table_exists cloud_config; then
            if ! check_if_data_in_column_of_table_exists cloud_config cc_id 39; then
                echo " -- db change : insert into cloud_config(cc_id, cc_key, cc_value) values (39, 'deprovision_pause', '50')"
                run_sql "insert into cloud_config(cc_id, cc_key, cc_value) values (39, 'deprovision_pause', '50');"
            fi
        fi
	fi

	# 2  > UPDATE user_info set user_lang = 'en';
	echo " -- db change : UPDATE user_info set user_lang = 'en'"
	run_sql "UPDATE user_info set user_lang = 'en';"

	# 3  > ALTER TABLE user_info ADD user_wizard_name VARCHAR(255) AFTER user_capabilities;
	if ! check_column_in_table_exists user_info user_wizard_name; then
		echo " -- db change : ALTER TABLE user_info ADD user_wizard_name VARCHAR(255) AFTER user_capabilities"
		run_sql "ALTER TABLE user_info ADD user_wizard_name VARCHAR(255) AFTER user_capabilities;"
	fi

	# 4  > ALTER TABLE user_info ADD user_wizard_step INT(5) AFTER user_wizard_name;
	if ! check_column_in_table_exists user_info user_wizard_step; then
		echo " -- db change : ALTER TABLE user_info ADD user_wizard_step INT(5) AFTER user_wizard_name"
		run_sql "ALTER TABLE user_info ADD user_wizard_step INT(5) AFTER user_wizard_name;"
	fi

	# 5  > ALTER TABLE user_info ADD user_wizard_id INT(5) AFTER user_wizard_step;
	if ! check_column_in_table_exists user_info user_wizard_id; then
		echo " -- db change : ALTER TABLE user_info ADD user_wizard_id INT(5) AFTER user_wizard_step"
		run_sql "ALTER TABLE user_info ADD user_wizard_id INT(5) AFTER user_wizard_step;"
	fi

	# 6  > ALTER TABLE appliance_info ADD appliance_wizard VARCHAR(255) AFTER appliance_comment;
	if ! check_column_in_table_exists appliance_info appliance_wizard; then
		echo " -- db change : ALTER TABLE appliance_info ADD appliance_wizard VARCHAR(255) AFTER appliance_comment"
		run_sql "ALTER TABLE appliance_info ADD appliance_wizard VARCHAR(255) AFTER appliance_comment;"
	fi

	# 7 > ALTER TABLE appliance_info MODIFY appliance_cpumodel VARCHAR(255);
	echo " -- db change : ALTER TABLE appliance_info MODIFY appliance_cpumodel VARCHAR(255)"
	run_sql "ALTER TABLE appliance_info MODIFY appliance_cpumodel VARCHAR(255);"

	# 8 > ALTER TABLE resource_info MODIFY resource_cpumodel VARCHAR(255);
	echo " -- db change : ALTER TABLE resource_info MODIFY resource_cpumodel VARCHAR(255)"
	run_sql "ALTER TABLE resource_info MODIFY resource_cpumodel VARCHAR(255);"

	# 10  > ALTER TABLE event_info MODIFY event_id BIGINT;
	echo " -- db change : ALTER TABLE event_info MODIFY event_id BIGINT"
	run_sql "ALTER TABLE event_info MODIFY event_id BIGINT;"


   echo "- Database sanity check for version 4.9 to 5.0 finished"

}







case "$1" in
	init)
		initialize_database
		;;
	backup)
		backup_database $2
		;;
	restore)
		restore_database $2
		;;
	drop)
		drop_database
		;;
	update)
		db_update
		;;
esac
