#!/bin/bash
# init script for the openQRM aoe-storage-plugin
#
# openQRM Enterprise developed by openQRM Enterprise GmbH.
#
# All source code and content (c) Copyright 2012, openQRM Enterprise GmbH unless specifically noted otherwise.
#
# This source code is released under the GNU General Public License version 2, unless otherwise agreed with openQRM Enterprise GmbH.
# The latest version of this license can be found here: src/doc/LICENSE.txt
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://openqrm-enterprise.com
#
# Copyright 2012, openQRM Enterprise GmbH <info@openqrm-enterprise.com>
#

OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/aoe-storage/include/openqrm-plugin-aoe-storage-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/aoe-storage/etc/openqrm-plugin-aoe-storage.conf

LINE_IFS='
'

function openqrm_plugin_aoe_storage_start() {
	echo "Starting the openQRM aoe-storage-plugin"
	touch $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/aoe-storage/.running
	if [ "$AOE_STORAGE_AUTO_START" == "yes" ]; then
		# make sure vbladed is stopped, not using the init script here because this may exit 1
		for VPID in `ps ax | grep vblade | grep -v grep | awk {' print $1 '}`; do
			kill $VPID
		done
		killall vblade 1>/dev/null 2>&1
		mkdir -p /var/run/vblade/
		if [ -x "/etc/init.d/vblade" ]; then
			if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
				invoke-rc.d vblade start
			else
				/etc/init.d/vblade start
			fi
		else
			if [ -f $VBLADECONF ]; then
				if which vbladed 1>/dev/null; then
					echo "Starting vblades ..."
					OLD_IFS=$IFS
					IFS=$LINE_IFS
					for VBLADE_L in `cat $VBLADECONF | grep -v '#' | sed '/^$/d'`; do
						V_INTERFACE=`echo $VBLADE_L | awk {' print $1 '}`
						V_SHELF=`echo $VBLADE_L | awk {' print $2 '}`
						V_SLOT=`echo $VBLADE_L | awk {' print $3 '}`
						V_IMAGE=`echo $VBLADE_L | awk {' print $4 '}`
						V_ALLOWED_MAC=`echo $VBLADE_L | awk {' print $5 '}`
						vbladed $V_SHELF $V_SLOT $V_INTERFACE $V_IMAGE
					done
					IFS=$OLD_IFS
				fi
			fi
		fi
	fi
}


function openqrm_plugin_aoe_storage_stop() {
	echo "Stopping the openQRM aoe-storage-plugin"
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/aoe-storage/.running
	if [ "$AOE_STORAGE_AUTO_START" == "yes" ]; then
		for VPID in `ps ax | grep vblade | grep -v grep | awk {' print $1 '}`; do
			kill $VPID
		done
		if [ -x "/etc/init.d/vblade" ]; then
			/etc/init.d/vblade stop
		else
			if [ -f $VBLADECONF ]; then
				echo "Stopping vblades ..."
				OLD_IFS=$IFS
				IFS=$LINE_IFS
				for VBLADE_L in `cat $VBLADECONF | grep -v '#' | sed '/^$/d'`; do
					V_INTERFACE=`echo $VBLADE_L | awk {' print $1 '}`
					V_SHELF=`echo $VBLADE_L | awk {' print $2 '}`
					V_SLOT=`echo $VBLADE_L | awk {' print $3 '}`
					V_IMAGE=`echo $VBLADE_L | awk {' print $4 '}`
					V_ALLOWED_MAC=`echo $VBLADE_L | awk {' print $5 '}`
					for VBLADE_PID in `ps ax | grep vblade | grep -w $V_IMAGE | awk {' print $1 '}`; do
						kill $VBLADE_PID
					done
				done
				IFS=$OLD_IFS
			fi
			killall vblade 1>/dev/null 2>&1
		fi
	fi
}

function openqrm_plugin_aoe_storage_uninstall() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "aoe-storage: Please give a username to uninstall the plugin : "
		read USERNAME
		echo
		echo -n "aoe-storage: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Uninstalling the openQRM aoe-storage-plugin"
	openqrm_plugin_aoe_storage_stop
	openqrm_server_remove_deployment_type $USERNAME $PASSWORD aoe-deployment
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/aoe-storage
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/root-mount.aoe-deployment
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image.aoe-deployment.php
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/boot-service-aoe-storage.tgz
	# remove only if lvm-storage is not enabled
	if ! ls $OPENQRM_SERVER_BASE_DIR/openqrm/web/base/plugins | grep lvm-storage 1>/dev/null 2>&1; then
		rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/aoe-interfaces
		rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/aoe-discover
		rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/aoe-stat
		rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/aoe-mkdevs
		rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/aoe-mkshelf
	fi
}

function openqrm_plugin_aoe_storage_init() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "aoe-storage: Please give a username to init the plugin : "
		read USERNAME
		echo
		echo -n "aoe-storage: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Initializing the openQRM aoe-storage-plugin"
	openqrm_server_add_deployment_type $USERNAME $PASSWORD aoe-deployment aoe-deployment "Aoe-root deployment" aoe-storage "Aoe/Coraid Storage"
	# linking the web dir
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/aoe-storage/web $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/aoe-storage
	# linking the boot-service
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/aoe-storage/web/boot-service-aoe-storage.tgz $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/boot-service-aoe-storage.tgz
	# linking the root mount hook
	chmod +x $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/aoe-storage/web/root-mount.aoe-deployment
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/aoe-storage/web/root-mount.aoe-deployment $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/root-mount.aoe-deployment
	# linking the image-menu
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/aoe-storage/web/image.aoe-deployment.php $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image.aoe-deployment.php

	# copying aoe-interfaces to boot-service dir
	if [ ! -x $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/aoe-interfaces ]; then
		cp -f `which aoe-interfaces` $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/
	fi
	# copying aoe-discover to boot-service dir
	if [ ! -x $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/aoe-discover ]; then
		cp -f `which aoe-discover` $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/
	fi
	# copying aoe-stat to boot-service dir
	if [ ! -x $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/aoe-stat ]; then
		cp -f `which aoe-stat` $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/
	fi
	# copying aoe-mkdevs to boot-service dir
	if [ ! -x $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/aoe-mkdevs ]; then
		cp -f `which aoe-mkdevs` $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/
		# remove the axwwww from the ps cmd in aoe-mkdevs
		sed -i -e "s/axwwww//g" $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/aoe-mkdevs
	fi
	# copying aoe-mkshelf to boot-service dir
	if [ ! -x $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/aoe-mkshelf ]; then
		cp -f `which aoe-mkshelf` $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/
		# remove the axwwww from the ps cmd in aoe-mkshelf
		sed -i -e "s/axwwww//g" $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/aoe-mkshelf
	fi
	# create storage dir for stat files
	mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/aoe-storage/web/storage
	chmod 777 $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/aoe-storage/web/storage
	
}

USER=$2
PASS=$3


case "$1" in
	start)
		openqrm_plugin_aoe_storage_start
		;;
	stop)
		openqrm_plugin_aoe_storage_stop
		;;
	restart)
		openqrm_plugin_aoe_storage_stop
		sleep 1
		openqrm_plugin_aoe_storage_start
		;;
	init)
		openqrm_plugin_aoe_storage_init $USER $PASS
		;;
	uninstall)
		openqrm_plugin_aoe_storage_uninstall $USER $PASS
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?
