#!/bin/bash
#
# This file is part of openQRM.
#
# openQRM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation.
#
# openQRM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openQRM.  If not, see <http://www.gnu.org/licenses/>.
#
# init script for the openQRM opsi-plugin
#
# Copyright 2011, openQRM Enterprise GmbH <info@openqrm-enterprise.com>

OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/opsi/include/openqrm-plugin-opsi-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/opsi/etc/openqrm-plugin-opsi.conf
# get the ip config
openqrm_server_get_config
export resource_openqrmserver=$OPENQRM_SERVER_IP_ADDRESS
export LANG=C
# define wget to use with https
if [ "$OPENQRM_WEB_PROTOCOL" == "https" ]; then
	WGET_NO_CERT_CHECK="--no-check-certificate"
fi

function openqrm_plugin_opsi_start() {
	echo "Starting the openQRM opsi-plugin"
	touch $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/opsi/.running
}


function openqrm_plugin_opsi_stop() {
	echo "Stopping the openQRM opsi-plugin"
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/opsi/.running
}

function openqrm_plugin_opsi_uninstall() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "opsi: Please give a username to uninstall the plugin : "
		read USERNAME
		echo
		echo -n "opsi: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Uninstalling the openQRM opsi-plugin"
	openqrm_plugin_opsi_stop
	openqrm_server_remove_deployment_type $USERNAME $PASSWORD opsi-deployment
	# removing the table
	if ! wget -q $WGET_NO_CERT_CHECK -O /dev/null --http-user=$USERNAME --http-password=$PASSWORD "$OPENQRM_WEB_PROTOCOL://$resource_openqrmserver/openqrm/base/plugins/opsi/opsi-action.php?opsi_command=uninstall"; then
		opsi_log init "ERROR: Could not drop the opsi-plugin tables in the database!"
		return 1
	fi
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/opsi
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/boot-service-opsi.tgz
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image.opsi-deployment.php
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/template.opsi-deployment.php

}

function openqrm_plugin_opsi_init() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "opsi: Please give a username to init the plugin : "
		read USERNAME
		echo
		echo -n "opsi: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Initializing the openQRM opsi-plugin"
	openqrm_server_add_deployment_type $USERNAME $PASSWORD opsi-deployment opsi-deployment "Opsi Windows deployment" opsi "Physical local disk (Opsi)"
	# linking the web dir
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/opsi/web $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/opsi
	# creating the table
	if ! wget -q $WGET_NO_CERT_CHECK -O /dev/null --http-user=$USERNAME --http-password=$PASSWORD "$OPENQRM_WEB_PROTOCOL://$resource_openqrmserver/openqrm/base/plugins/opsi/opsi-action.php?opsi_command=init"; then
		opsi_log init "ERROR: Could not create the opsi-plugin tables in the database!"
		rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/opsi
		return 1
	fi
	# link the boot-service
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/opsi/web/boot-service-opsi.tgz $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/boot-service-opsi.tgz
	# link the image + template hooks
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/opsi/web/image.opsi-deployment.php $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image.opsi-deployment.php
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/opsi/web/template.opsi-deployment.php $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/template.opsi-deployment.php
	# place for the storage stat files
	mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/opsi/web/storage
	chmod -R 777 $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/opsi/web/storage
}

USER=$2
PASS=$3

case "$1" in
	start)
		openqrm_plugin_opsi_start
		;;
	stop)
		openqrm_plugin_opsi_stop
		;;
	restart)
		openqrm_plugin_opsi_stop
		sleep 1
		openqrm_plugin_opsi_start
		;;
	init)
		openqrm_plugin_opsi_init $USER $PASS
		;;
	uninstall)
		openqrm_plugin_opsi_uninstall $USER $PASS
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?




