#!/bin/bash
# this is the functions file for the wakeuponlan-plugin
#
#
# This file is part of openQRM.
#
# openQRM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation.
#
# openQRM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openQRM.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2010, openQRM Enterprise GmbH <info@openqrm-enterprise.com>

WAKEUPONLAN_LOCK_FILE=/var/run/wakeuponlan/wakeuponlan-plugin.lock
WAKEUPONLAN_LOCK_DELAY=5
WAKEUPONLAN_LOCK_RETRY=100
WAKEUPONLAN_LOCK_TIMEOUT=500
################ common wakeuponlan functions

# logs for wakeuponlan
function wakeuponlan_log() {
	local COMPONENT=$1
	shift
	local MESSAGE=$@
	logger -i -t "wakeuponlan plug-in" "$COMPONENT : $MESSAGE"
}


# locking function
function wakeuponlan_lock() {
	local COMMAND=$1
	local RET=1

	if [ ! -d `dirname $WAKEUPONLAN_LOCK_FILE` ]; then
		mkdir -p `dirname $WAKEUPONLAN_LOCK_FILE`
	fi
	case "$COMMAND" in
		aquire)
				lockfile -s $WAKEUPONLAN_LOCK_DELAY -r $WAKEUPONLAN_LOCK_RETRY -l $WAKEUPONLAN_LOCK_TIMEOUT $WAKEUPONLAN_LOCK_FILE
				RET=$?
				wakeuponlan_log wakeuponlan_lock "Aquired the lock"
				return $RET
				;;
		release)
				/bin/rm -f $WAKEUPONLAN_LOCK_FILE
				RET=$?
				wakeuponlan_log wakeuponlan_lock "Released the lock"
				return $RET
				;;
		*)
			wakeuponlan_log wakeuponlan_lock "No such command. Try 'aquire' or 'release'"
			return 1
			;;
	esac
}



################ wakeuponlan functions


