#!/bin/bash
#
# openQRM Enterprise developed by openQRM Enterprise GmbH.
#
# All source code and content (c) Copyright 2012, openQRM Enterprise GmbH unless specifically noted otherwise.
#
# This source code is released under the GNU General Public License version 2, unless otherwise agreed with openQRM Enterprise GmbH.
# The latest version of this license can be found here: src/doc/LICENSE.txt
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://openqrm-enterprise.com
#
# Copyright 2012, openQRM Enterprise GmbH <info@openqrm-enterprise.com>

OPSI_LOCK_FILE=/var/run/opsi/opsi-plugin.lock
OPSI_LOCK_DELAY=5
OPSI_LOCK_RETRY=100
OPSI_LOCK_TIMEOUT=500
################ common opsi functions

# logs for opsi
function opsi_log() {
	local COMPONENT=$1
	shift
	local MESSAGE=$@
	logger -i -t "opsi plug-in" "$COMPONENT : $MESSAGE"
}


# locking function
function opsi_lock() {
	local COMMAND=$1
	local RET=1

	if [ ! -d `dirname $OPSI_LOCK_FILE` ]; then
		mkdir -p `dirname $OPSI_LOCK_FILE`
	fi
	case "$COMMAND" in
		aquire)
				lockfile -s $OPSI_LOCK_DELAY -r $OPSI_LOCK_RETRY -l $OPSI_LOCK_TIMEOUT $OPSI_LOCK_FILE
				RET=$?
				opsi_log opsi_lock "Aquired the lock"
				return $RET
				;;
		release)
				/bin/rm -f $OPSI_LOCK_FILE
				RET=$?
				opsi_log opsi_lock "Released the lock"
				return $RET
				;;
		*)
			opsi_log opsi_lock "No such command. Try 'aquire' or 'release'"
			return 1
			;;
	esac
}



################ opsi functions


