#!/bin/bash
#
# openQRM Enterprise developed by openQRM Enterprise GmbH.
#
# All source code and content (c) Copyright 2012, openQRM Enterprise GmbH unless specifically noted otherwise.
#
# This source code is released under the GNU General Public License version 2, unless otherwise agreed with openQRM Enterprise GmbH.
# The latest version of this license can be found here: src/doc/LICENSE.txt
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://openqrm-enterprise.com
#
# Copyright 2012, openQRM Enterprise GmbH <info@openqrm-enterprise.com>

FAI_LOCK_FILE=/var/run/fai/fai-plugin.lock
FAI_LOCK_DELAY=5
FAI_LOCK_RETRY=100
FAI_LOCK_TIMEOUT=500
################ common fai functions

# logs for fai
function fai_log() {
	local COMPONENT=$1
	shift
	local MESSAGE=$@
	logger -i -t "fai plug-in" "$COMPONENT : $MESSAGE"
}


# locking function
function fai_lock() {
	local COMMAND=$1
	local RET=1

	if [ ! -d `dirname $FAI_LOCK_FILE` ]; then
		mkdir -p `dirname $FAI_LOCK_FILE`
	fi
	case "$COMMAND" in
		aquire)
				lockfile -s $FAI_LOCK_DELAY -r $FAI_LOCK_RETRY -l $FAI_LOCK_TIMEOUT $FAI_LOCK_FILE
				RET=$?
				fai_log fai_lock "Aquired the lock"
				return $RET
				;;
		release)
				/bin/rm -f $FAI_LOCK_FILE
				RET=$?
				fai_log fai_lock "Released the lock"
				return $RET
				;;
		*)
			fai_log fai_lock "No such command. Try 'aquire' or 'release'"
			return 1
			;;
	esac
}



################ fai functions


