#!/bin/bash
# this is the functions file for the windows-plugin
#
# openQRM Enterprise developed by openQRM Enterprise GmbH.
#
# All source code and content (c) Copyright 2012, openQRM Enterprise GmbH unless specifically noted otherwise.
#
# This source code is released under the GNU General Public License version 2, unless otherwise agreed with openQRM Enterprise GmbH.
# The latest version of this license can be found here: src/doc/LICENSE.txt
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://openqrm-enterprise.com
#
# Copyright 2012, openQRM Enterprise GmbH <info@openqrm-enterprise.com>
#


# some definitions
DEFAULT_IMAGE_SIZE=5000
WINDOWS_LOCK_FILE=/var/run/windows/windows-plugin.lock
WINDOWS_LOCK_DELAY=5
WINDOWS_LOCK_RETRY=100
WINDOWS_LOCK_TIMEOUT=500

################ common windows functions

# logs for windows
function windows_log() {
	local COMPONENT=$1
	shift
	local MESSAGE=$@
	logger -i -t "windows plug-in" "$COMPONENT : $MESSAGE"
}


# locking function
function windows_lock() {
	local COMMAND=$1
	local RET=1

	if [ ! -d `dirname $WINDOWS_LOCK_FILE` ]; then
		mkdir -p `dirname $WINDOWS_LOCK_FILE`
	fi
	case "$COMMAND" in
		aquire)
				lockfile -s $WINDOWS_LOCK_DELAY -r $WINDOWS_LOCK_RETRY -l $WINDOWS_LOCK_TIMEOUT $WINDOWS_LOCK_FILE
				RET=$?
				windows_log windows_lock "Aquired the lock"
				return $RET
				;;
		release)
				/bin/rm -f $WINDOWS_LOCK_FILE
				RET=$?
				windows_log windows_lock "Released the lock"
				return $RET
				;;
		*)
			windows_log windows_lock "No such command. Try 'aquire' or 'release'"
			return 1
			;;
	esac
}



################ windows functions











