#!/bin/bash
# this is the functions file for the openvz-storage-plugin
#
# This file is part of openQRM.
#
# openQRM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation.
#
# openQRM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openQRM.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2011, openQRM Enterprise GmbH <info@openqrm-enterprise.com>
#


# some definitions
DEFAULT_IMAGE_SIZE=5000
OPENVZ_LOCK_FILE=/var/run/openvz-storage/openvz-storage-plugin.lock
OPENVZ_LOCK_DELAY=5
OPENVZ_LOCK_RETRY=100
OPENVZ_LOCK_TIMEOUT=500
LV_SIZE_DEFAULT=5000

# which screen binary to use
if [ -x /usr/bin/screen.real ]; then
	RUNSCREEN="/usr/bin/screen.real"
else
	RUNSCREEN=`which screen`
fi

################ common openvz-storage functions

# logs for openvz_storage
function openvz_log() {
	local COMPONENT=$1
	shift
	local MESSAGE=$@
	logger -i -t "openvz-storage plug-in" "$COMPONENT : $MESSAGE"
}


# locking function
function openvz_lock() {
	local COMMAND=$1
	local RET=1

	if [ ! -d `dirname $OPENVZ_LOCK_FILE` ]; then
		mkdir -p `dirname $OPENVZ_LOCK_FILE`
	fi
	case "$COMMAND" in
		aquire)
				lockfile -s $OPENVZ_LOCK_DELAY -r $OPENVZ_LOCK_RETRY -l $OPENVZ_LOCK_TIMEOUT $OPENVZ_LOCK_FILE
				RET=$?
				openvz_log openvz_lock "Aquired the lock"
				return $RET
				;;
		release)
				/bin/rm -f $OPENVZ_LOCK_FILE
				RET=$?
				openvz_log openvz_lock "Released the lock"
				return $RET
				;;
		*)
			openvz_log openvz_lock "No such command. Try 'aquire' or 'release'"
			return 1
			;;
	esac
}



################ openvz-storage functions



